### ISSUE TITLE
Add pom.xml file so that we can build from the command line.

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#10]
To add this project to Eclipse's Continuous Integration (CI) system, we need to be able to build it from the command line.

To do this, I need to build from the command line using Tycho, which uses Maven.

(Historical note: long ago, the Ptolemy Project had a Tcl/Tk based IDE called Tycho)

To create a Maven pom.xml file, the Eclipse Tycho Tutorial at http://www.vogella.com/tutorials/EclipseTycho/article.html#maventycho_generatepom1 suggests that we do: 
> mvn org.eclipse.tycho:tycho-pomgenerator-plugin:generate-poms -DgroupId=triquetrum

I checked out a clean Triquetrum tree, ran the above command and the pom.xml was created:
> bash-3.2$ git clone https://github.com/eclipse/triquetrum/
> Cloning into 'triquetrum'...
> remote: Counting objects: 897, done.        
> remote: Total 897 (delta 0), reused 0 (delta 0), pack-reused 896        
> Receiving objects: 100% (897/897), 7.63 MiB | 877.00 KiB/s, done.
> Resolving deltas: 100% (294/294), done.
> Checking connectivity... done.
> bash-3.2$ cd triquetrum/
> bash-3.2$ mvn org.eclipse.tycho:tycho-pomgenerator-plugin:generate-poms -DgroupId=triquetrum
> [INFO] Scanning for projects...
> [INFO]
> [INFO] ------------------------------------------------------------------------
> [INFO] Building Maven Stub Project (No POM) 1
> [INFO] ------------------------------------------------------------------------
> [INFO]
> [INFO] --- tycho-pomgenerator-plugin:0.24.0:generate-poms (default-cli) @ standalone-pom ---
> [INFO] Scanning /Users/cxh/src/triquetrum/tmp/triquetrum basedir
> [INFO] Scanning /Users/cxh/src/triquetrum/tmp/triquetrum/.git basedir
> [INFO] Scanning /Users/cxh/src/triquetrum/tmp/triquetrum/.git/branches basedir
> [INFO] Scanning /Users/cxh/src/triquetrum/tmp/triquetrum/.git/hooks basedir
> [INFO] Scanning /Users/cxh/src/triquetrum/tmp/triquetrum/.git/info basedir
> [INFO] Scanning /Users/cxh/src/triquetrum/tmp/triquetrum/.git/logs basedir
> [INFO] Scanning /Users/cxh/src/triquetrum/tmp/triquetrum/.git/logs/refs basedir
> [INFO] Scanning /Users/cxh/src/triquetrum/tmp/triquetrum/.git/logs/refs/heads basedir
> [INFO] Scanning /Users/cxh/src/triquetrum/tmp/triquetrum/.git/logs/refs/remotes basedir
> [INFO] Scanning /Users/cxh/src/triquetrum/tmp/triquetrum/.git/logs/refs/remotes/origin basedir
> [INFO] Scanning /Users/cxh/src/triquetrum/tmp/triquetrum/.git/objects basedir
> [INFO] Scanning /Users/cxh/src/triquetrum/tmp/triquetrum/.git/objects/info basedir
> [INFO] Scanning /Users/cxh/src/triquetrum/tmp/triquetrum/.git/objects/pack basedir
> [INFO] Scanning /Users/cxh/src/triquetrum/tmp/triquetrum/.git/refs basedir
> [INFO] Scanning /Users/cxh/src/triquetrum/tmp/triquetrum/.git/refs/heads basedir
> [INFO] Scanning /Users/cxh/src/triquetrum/tmp/triquetrum/.git/refs/remotes basedir
> [INFO] Scanning /Users/cxh/src/triquetrum/tmp/triquetrum/.git/refs/remotes/origin basedir
> [INFO] Scanning /Users/cxh/src/triquetrum/tmp/triquetrum/.git/refs/tags basedir
> [INFO] Scanning /Users/cxh/src/triquetrum/tmp/triquetrum/org.eclipse.triquetrum.target.platform basedir
> [INFO] Scanning /Users/cxh/src/triquetrum/tmp/triquetrum/org.eclipse.triquetrum.target.platform/target basedir
> [INFO] Scanning /Users/cxh/src/triquetrum/tmp/triquetrum/org.eclipse.triquetrum.target.platform/target/plugins basedir
> [INFO] ------------------------------------------------------------------------
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 0.666 s
> [INFO] Finished at: 2016-01-18T11:01:02-08:00
> [INFO] Final Memory: 12M/309M
> [INFO] ------------------------------------------------------------------------

To avoid creating pom.xml files in each directory, https://wiki.eclipse.org/Tycho/Release_Notes/0.24#POM-less_Tycho_builds suggests creating a .mvn/extensions.xml file, which I did:
> bash-3.2$ mkdir .mvn
> bash-3.2$ cp ../../triquetrum/.mvn/extensions.xml .mvn

Ok, so the next step is to run Maven.

The Eclipse Tycho Tutorial states:
> "Tip: It is not recommended to use the mvn clean install command, instead you should use mvn clean verify. If you would use the install option, the build result would be installed in your local Maven repository and this can lead to build problems."

The tutorial also states:
> "Warning If you try to execute this POM file, the build fail because you have not yet configured your dependencies." 

Indeed, just running "mvn clean" fails because "package ptolemy.data 10.1.0" is not found:
> bash-3.2$ mvn clean
> [INFO] Scanning for projects...
> [WARNING] No explicit target runtime environment configuration. Build is platform dependent.
> [WARNING] No explicit target runtime environment configuration. Build is platform dependent.
> [WARNING] No explicit target runtime environment configuration. Build is platform dependent.
> [WARNING] No explicit target runtime environment configuration. Build is platform dependent.
> [WARNING] No explicit target runtime environment configuration. Build is platform dependent.
> [WARNING] No explicit target runtime environment configuration. Build is platform dependent.
> [WARNING] No explicit target runtime environment configuration. Build is platform dependent.
> [WARNING] No explicit target runtime environment configuration. Build is platform dependent.
> [WARNING] No explicit target runtime environment configuration. Build is platform dependent.
> [WARNING] No explicit target runtime environment configuration. Build is platform dependent.
> [WARNING] No explicit target runtime environment configuration. Build is platform dependent.
> [WARNING] No explicit target runtime environment configuration. Build is platform dependent.
(BTW - I looked at the ICE pom.xml to attempt to set the target for Triquetrum, but had no success.)
> [INFO] Computing target platform for MavenProject: triquetrum:org.eclipse.triquetrum.common:1.0.0-SNAPSHOT @ /Users/cxh/src/triquetrum/tmp/triquetrum/org.eclipse.triquetrum.common/pom.xml
> [INFO] Resolving dependencies of MavenProject: triquetrum:org.eclipse.triquetrum.common:1.0.0-SNAPSHOT @ /Users/cxh/src/triquetrum/tmp/triquetrum/org.eclipse.triquetrum.common/pom.xml
> [INFO] {osgi.os=macosx, osgi.ws=cocoa, org.eclipse.update.install.features=true, osgi.arch=x86_64}
> [ERROR] Cannot resolve project dependencies:
> [ERROR]   Software being installed: org.eclipse.triquetrum.common 1.0.0.qualifier
> [ERROR]   Missing requirement: org.eclipse.triquetrum.common 1.0.0.qualifier requires 'package ptolemy.data 10.1.0' but it could not be found
> [ERROR]
> [ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
> [ERROR] Cannot resolve dependencies of MavenProject: triquetrum:org.eclipse.triquetrum.common:1.0.0-SNAPSHOT @ /Users/cxh/src/triquetrum/tmp/triquetrum/org.eclipse.triquetrum.common/pom.xml: See log for details -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
> bash-3.2$
Ok, not surprising, triquetrum/org.eclipse.triquetrum.common/META-INF/MANIFEST.MF contains:

> Import-Package: ptolemy.data;version="10.1.0",
>  ptolemy.kernel.util

triquetrum/./org.eclipse.triquetrum.target.platform/target/plugins/ptolemy.core_11.0.0.201511291558.jar is the jar file that contains ptolemy.data.   That jar files MANIFEST.MF includes:

> Export-Package: org.ptolemy.osgi;version="11.0.0",ptolemy.actor;versio
>  n="11.0.0",ptolemy.actor.parameters;version="11.0.0",ptolemy.actor.sc
>  hed;version="11.0.0",ptolemy.actor.util;version="11.0.0",ptolemy.data
>  ;version="11.0.0",ptolemy.data.expr;version="11.0.0",ptolemy.data.typ
>  e;version="11.0.0",ptolemy.data.unit;version="11.0.0",ptolemy.graph;v
>  ersion="11.0.0",ptolemy.graph.analysis;version="11.0.0",ptolemy.graph
>  .analysis.analyzer;version="11.0.0",ptolemy.graph.analysis.strategy;v
>  ersion="11.0.0",ptolemy.graph.mapping;version="11.0.0",ptolemy.kernel
>  ;version="11.0.0",ptolemy.kernel.attributes;version="11.0.0",ptolemy.
>  kernel.undo;version="11.0.0",ptolemy.kernel.util;version="11.0.0",pto
>  lemy.math;version="11.0.0",ptolemy.util;version="11.0.0"
Note that the MANIFEST.MF above has "ptolemy.data.expr;version="11.0.0" and we are looking for the 10.1.0 version, but this should work (right?)

So, now the question is: how to get Tycho to know where these dependencies are.

In a perfect world, we could use the Maven dependency facility in the pom.xml file, but this is not how Eclipse and Tycho work for various good reasons.

It looks to me like I would need to put these up on an Eclipse p2 server.  I'm assuming that I could host one of these?  Is this correct?  There was also some ideas of using jetty to bring up a local p2 server for our jar files.

The p2-maven-plugin at http://projects.reficio.org/p2-maven-plugin/1.1.0/manual.html looks useful.

This stackoverflow post looks helpful: http://stackoverflow.com/questions/13268213/how-to-use-directory-containing-third-party-bundles-in-a-tycho-build

As does this, but it is not a perfect fit: https://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting

Jay suggested:

> I think you are on the right track. What I did in ICE to handle third party dependencies that weren't available at a p2 site was to create an org.eclipse.ice.dependencies bundle
>
> https://github.com/jayjaybillings/ICEDeps/tree/master/org.eclipse.ice.dependencies
>
> This bundle includes the dependencies on its classpath and exports them. Then, any other bundle that uses them just does an Import-Package call in their manifest and is good to go.

Erwin wrote:
> Great that you're taking up this task. I think that to get things working quickly, Jay's approach is the easiest for now, i.e. we put all dependencies as jars inside a wrapper bundle that then exports all Java packages from there. It would be a straightforward redefinition of what is now org.eclipse.triquetrum.target.platform.

> A very promising tool to get a flexible build repository is Package Drone, presented at eclipse con last year.
> It offers a multi-"protocol" repository including p2, std maven etc.
> But I guess that would take some experimenting first to get it working.

I'll create a branch with my pom.xml and .mvn/extension.xml file.

**Comment by cxbrooks** [comment]
The current status is that 

```
git clone https://github.com/eclipse/triquetrum
cd triquetrum
mvn -N install
mvn install
```
works.  It is no longer necessary to check out cxbrooks/triquetrumDeps.

Next up, work on the target.

**Comment by erwindl0** [comment]
I think this ticket can be closed now, with a working Tycho build that can be run from the command line and on our Hudson instance, producing RCP zips?

**Comment by cxbrooks** [comment]
Yep, we can close this one.  We have a downloads link on the GitHub page and on the Wiki.
