### ISSUE TITLE
Need a way for OSGi bundles to add to the MoML Filters

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#113]
A Java package can appear at most in one loaded OSGi bundle in an application.

We have a number of Ptolemy II OSGi bundles that have completed the Contribution Questionnaire process for third party libraries (see https://wiki.eclipse.org/Development_Resources/Contribution_Questionnaire#Third_Party_Libraries and Bug #70: Ipzilla issues for Triquetrum third party code)

If someone wants to add a Ptolemy actor that is in one of the packages in one of the bundles that have passed review, then either the bundle needs to be re-reviewed or the actor needs to be renamed.

In general, we don't want to request frequent reviews.

So, we should augment the system so that a bundle can register a MoMLFilter that will cause the MoMLParser to read in a model file that refers to the actor with the old ptII package name and instead look up the new Triquetrum package name.

See also  https://wiki.eclipse.org/Triquetrum/Ptolemy/Porting

**Comment by erwindl0** [comment]
I wrote a short text about how to address this situation on [our wiki](https://wiki.eclipse.org/Triquetrum/Ptolemy/Porting#Solving_the_ptolemy.actor.lib_package_naming_issue) .

Is that sufficient for this issue?

**Comment by cxbrooks** [comment]
To close this, I want to try out the process.

**Comment by cxbrooks** [comment]
My previous comment was on the wrong bug.

We can close this bug because we have Bug #90 Document the process of adding an actor.
