### ISSUE TITLE
Sign Triquetrum Bundles

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#128]
https://www.eclipse.org/projects/handbook/#resources-builds says:

> Where technically sensible, all downloadable artifacts should be signed by an Eclipse Foundation-provided certificate.

and has a link to https://wiki.eclipse.org/JAR_Signing

I'm putting this on the Science2016Release Milestone, but we can drop it if need be.

**Comment by erwindl0** [comment]
A detailed description of how to set that up : http://www.codetrails.com/blog/sign-your-eclipse-project

**Comment by cxbrooks** [comment]
See also https://wiki.eclipse.org/IT_Infrastructure_Doc#Sign_my_plugins.2FZIP_files.3F

**Comment by cxbrooks** [comment]
I found that it was easiest to start with https://github.com/eclipse/ice/blob/master/org.eclipse.ice.parent/pom.xml 

One possible issue is that in Triquetrum, eclipse-jarsigner-plugin is version 1.0.1.  However, in Ice, it is 1.1.3.  When I tried 1.1.3, I got 

> [ERROR] Plugin org.eclipse.cbi.maven.plugins:eclipse-jarsigner-plugin:1.1.3 or one of its dependencies could not be resolved: Failure to find org.eclipse.cbi.maven.plugins:eclipse-jarsigner-plugin:jar:1.1.3 in http://download.eclipse.org/technology/m2e/maven/ was cached in the local repository, resolution will not be reattempted until the update interval of m2e-cbi has elapsed or updates are forced 

I updated the triquetrum Hudson build so that we are using the eclipse-sign profile.

I verified that the Mac download at https://hudson.eclipse.org/triquetrum/job/triquetrum/lastSuccessfulBuild/artifact/org.eclipse.triquetrum.repository/target/products/ has signed Triquetrum plugins and features.

To close this, we need to fix Bug #148 Make releases available on the Eclipse download server and Bug #145 Create a p2 update site and verify that the jars are signed.

In addition, we should sign the osgi-2-0 jar files with the Ptolemy II code signing certificate or create a separate issue with a later milestone.

**Comment by cxbrooks** [comment]
The releases are available on the the Eclipse download server and at least the Mac release contains signed plug-ins

The p2 update site contains signed plug-ins.

I created bug #178 Sign the Ptolemy Plug-ins, which has a 2017 Spring Release milestone.

Closing this one.
