### ISSUE TITLE
Add about.html files

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#132]
The checklist at https://wiki.eclipse.org/Development_Resources/HOWTO/Release_Reviews#Checklist states:

> Every bundles contains an about.html file as required by [A Guide to the Legal Documentation for Eclipse-Based Content](https://www.eclipse.org/legal/guidetolegaldoc.php).

The legal guide has a checklist for Abouts:

- [x] 'Every plug-in has an "about.html", usually the standard one.'
- [x] 'Every plug-in with a non-standard "about.html" contains the additional referenced license files.'
- [x] 'Every JAR’ed plug-in stores linked files in "about_files"'

**Comment by cxbrooks** [comment]
Closing this, though it will need to be checked when we are ready to submit to a release review.

**Comment by cxbrooks** [comment]
Check that any plug-ins that use Ptolemy jars also have the Ptolemy license.

**Comment by cxbrooks** [comment]
I modified the diva and ptolemy plugins so that they have about.html files, which means that the Triquetrum plugins don't need about.html files that have the Ptolemy license.

I think this is ready to be closed.  I'm assigning this to Erwin so that he may check it against  A [Guide to the Legal Documentation for Eclipse-Based Content](https://www.eclipse.org/legal/guidetolegaldoc.php) or close it.

**Comment by erwindl0** [comment]
I think this is complete indeed.
