### ISSUE TITLE
Source files require license notices

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#135]
The checklist at https://wiki.eclipse.org/Development_Resources/HOWTO/Release_Reviews#Checklist states:

> Every bundles contains an about.html file as required by [A Guide to the Legal Documentation for Eclipse-Based Content](https://www.eclipse.org/legal/guidetolegaldoc.php).

The guide to legal docs says:

> 4.4 Notices in source code
> 
> The Basics:
> 
> Where practical, all source code (which includes Java source as well other types of files such as XML, HTML, etc.) should contain appropriate copyright and license notices as well information on each contribution.
> 
> The Details:
> 
> The standard format for these notices can be found at www.eclipse.org > Legal Stuff > [Default Copyright and License Notice](https://www.eclipse.org/legal/copyrightandlicensenotice.php).
> 
> If the source is to be licensed under a license other than or in addition to the EPL, you must ensure that the Eclipse Foundation has approved the notice.
> 
> The Location:
> 
> In the source code.

**Comment by cxbrooks** [comment]
This looks like the right thing to use: https://wiki.eclipse.org/Development_Resources/How_to_Use_Eclipse_Copyright_Tool

**Comment by erwindl0** [comment]
Gone through all the java files, build.properties and feature/plugin xmls (the things that the "Fix Copyright" tool works on).

Mostly a matter of adding 2016 in many of the older headers.

Should be ok now.

**Comment by cxbrooks** [comment]
At a glance, the .java, build.properties and feature/plugin xmls have a copyright and year.
