### ISSUE TITLE
Python connectivity fails when launching workflow editor from eclipse workspace

### ISSUE THREAD

**Issue by erwindl0** [eclipse/triquetrum#141]
This is on Windows 10 64 bit, with python 2.7.3 32 bit.

When exporting the Triq RCP product (for win 64 bit), running  a workflow with a python actor runs well.

When launching the product from inside my Triquetrum workspace I can try python scripts in 2 ways, in the same running equinox instance :
- using the osgi console runScript test command (from org.eclipse.triquetrum.python.service.example): then it works fine
- using the same workflow as mentioned above and launching it from the editor : the PythonService.getActiveClient(int) never obtains an active response.

In that last case, the getActiveClient() keeps getting errors in the line :        
`final Object active = client.request("isActive", new Object[] { "unused" }); `

The error is :
"org.apache.xmlrpc.XmlRpcException: Failed to read servers response: Connection refused: connect". 
The retry loop keeps on trying until timeout...

The python.exe process is running, and is never terminated.

When running the script using the runScript test cmd, the same code gets executed as in the workflow actor, from inside the same running platform. And then the client.request() invocation has a success response form the 1st try. (and the python.exe is correctly terminated at the end as well)

**Comment by erwindl0** [comment]
To reproduce and/or investigate

The test model is in [testPython.zip](https://github.com/eclipse/triquetrum/files/465897/testPython.zip)

1. update your local triq repo to current master
2. run the /org.eclipse.triquetrum.repository/Triquetrum.product from inside your workspace
3. create a plain test project in your triq editor RCP
4. unzip and copy the attached model in your test project and run it

You should get a timeout exception after a while.

Now export the product and run it outside of your workspace and try the same. The python actor should work fine then.

Now back in your eclipse workspace, add the bundle org.eclipse.triquetrum.python.service.example to your launch configuration and run again from your workspace. The workflow should still go in timeout, but now you can try from the OSGi console something like : 

osgi> runScript helloworld input1=hi input2=ho
hello world : hi and ho
{output3={key1=hi, key2=ho}, output4=hey, output1=1, output2=[D@7c4c8b0d, output5={key1=hey there, key2=3, key3=[Ljava.lang.Object;@1e2bb6c6}, output0=1}
osgi>

i.e. the script integration works fine then, from the same running platform as the RCP editor.

**Comment by erwindl0** [comment]
Might be related to loading of system scripts by the python process somehow (although I fail to see the way the python process might be impacted by the "triq side" doing its thing from a test command or form an actor) : 

- when running from the runScript cmd (or external RPC) the python process consumes about 4.6 MB as indicated in windows task manager
- when running from a workflow, the python process sticks to 1.1 MB

**Comment by jonahkichwacoders** [comment]
Finally found some time to look at this. 

One additional setup step is to configure the Python Actor block to have the script path set to helloworld within this location in git: examples/org.eclipse.triquetrum.python.service.example/scripts/helloworld.py

**Comment by jonahkichwacoders** [comment]
When I run this workflow on Linux* using Python2.7 it just works.
Can't test Python3 as Python3 is not supported yet.

* I am using Xubuntu 16.04 and the system Python 2.7.12

I'll try in WIndows 10 next.

**Comment by jonahkichwacoders** [comment]
Looks like it is failing as described on Windows 10 with  Python 2.7.12 (from anaconda)

**Comment by jonahkichwacoders** [comment]
The problem looks like it is on the Python side. I can see the python processes running, but the process is not listening to the port.

**Comment by jonahkichwacoders** [comment]
The problem has to do with how the input on the python process is redirected. The problem is:

processBuilder.redirectInput(Redirect.INHERIT);

Now on to figure out why.

**Comment by jonahkichwacoders** [comment]
OK. I understand the problem and have a proposed fix. 

If you run in the dev environment without the -console (OSGi console) then there is no contention for stdin. But Python really shouldn't be inheriting stdin in this case and that is what the change is.

**Comment by erwindl0** [comment]
That's a great find! (if that is correct belgian english ;-) )

Op 9/22/2016 om 10:13 AM schreef Jonah Graham:

**Comment by erwindl0** [comment]
fixed with pull request #165
