### ISSUE TITLE
Create a new release record

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#146]
As per http://www.eclipse.org/projects/handbook/#release, we need to go to the [Triquetrum project page ](https://projects.eclipse.org/projects/technology.triquetrum) and under Committer Tools on the right select [Create a New Release](https://projects.eclipse.org/node/8907/create-release). 

To proceed, we need a release version number, which is probably 0.1.0.

**Comment by cxbrooks** [comment]
I made a pass through the Triquetrum Release Record at https://projects.eclipse.org/projects/technology.triquetrum/releases/0.1.0

Erwin pointed out the [ChemClipse 0.7.0 Release Record](https://projects.eclipse.org/projects/technology.chemclipse/releases/0.7.0/review) as an example.

To close this issue:
1. Erwin needs to make a pass through https://projects.eclipse.org/projects/technology.triquetrum/releases/0.1.0/edit
2. We need to address Bug #147 Review the UI Guidelines and Checklist
3. Erwin and I need to decide that the Release Record and source code are ready for review.

I'm assigning this to Erwin so he can make a pass through the Release Record.

**Comment by erwindl0** [comment]
I have gone through the release record and added some content about the 3 lines of work etc.
Christopher can you review my changes? As far as I can tell, the content should now be sufficient to describe our first release.

**Comment by erwindl0** [comment]
I have done the review of the UI guidelines and have added the gaps in the release record.

**Comment by cxbrooks** [comment]
The text in the release record looks good.  

I'm assigning this to Erwin for him to determine if before closing this issue, should we create issues for the gaps identified in the release record.
