### ISSUE TITLE
Review the UI Guidelines and Checklist

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#147]
The [Triquetrum 0.1.0 release plan](https://projects.eclipse.org/projects/technology.triquetrum/releases/0.1.0/edit) includes a section about Release Documentation:

> Usability
> Summarize the usability of the software. Usability in this sense is about using the software from the end-user's point-of-view, not the more academic sense of UI evaluation/testing. Summarize the user interface usability and the conformance to the [User Interface Guidelines](http://wiki.eclipse.org/User_Interface_Guidelines). If appropriate, include discussion of section 508 compliance (you can discuss multiple language support in the Internationalization section, below). Explain any deviations from the user interface guidelines and standards.

To close this, we need to:
1. Review the [User Interface Guidelines](http://wiki.eclipse.org/User_Interface_Guidelines)
2. Complete the [UI Checklist](https://wiki.eclipse.org/UI_Checklist)
3. Update the Usability section of the [Triquetrum 0.1.0 release plan](https://projects.eclipse.org/projects/technology.triquetrum/releases/0.1.0/edit)

**Comment by erwindl0** [comment]
review done and gaps are documented in the release record.

**Comment by cxbrooks** [comment]
(I accidentally posted this to the release record Bug #146, but edited that bug and am adding it here)

I'm assigning this to Erwin for him to determine if before closing this issue, should we create issues for the gaps identified in the release record.

**Comment by erwindl0** [comment]
Follow up for UI guideline gaps in #160.

This one can be closed then. We're in sufficient shape as-is for UI guidelines for a first release.
