### ISSUE TITLE
It is not possible to change a port between and input and an output

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#158]
From Bug #95:

It is not yet possible to change a port between input&output, and the current cfg dialog has some unergonomic duplicate concepts. I.e. an actor has an input port list and an output port list but still the user must check the port types as well.

I would leave that until after the release, as the solution for this involves a non-trivial change in the underlying EMF model.

**Comment by erwindl0** [comment]
Basic behavior is in place. The EMF model has been adapted to have one list of all ports, combined with getters for input ports and output ports. The actor config dialog now has a single table for all ports, with the checkboxes to mark them as input/output/multiport. When changing from input to output and vice-versa, the actor shape is updated after Ok-ing.

Two open issues remain : 
- how to block the properties of the ports defined in the actor code (similarly to Ptolemy vergil's approach, while allowing them to be editable for dynamically added ports. This seems to be difficult/impossible with EMF forms viewmodels. Maybe need to check out EMF Parsley that uses DSLs i.o. declarative models.
- define the port layout for ports that are both input&output (and what about ports that are marked as neither?

**Comment by erwindl0** [comment]
Christopher,

I've merged work that should fix most of the port type-changing issues:
- The actor configuration panel has been simplified to just show one port table.
- Ports can be changed between input&output (or both)
- Added a "direction" concept (similar to Ptolemy) to place ports on one of the 4 actor sides

Still to do : rotate the port shape to always point inwards for an input & outwards for an output.
For the moment it still always points from left-to-right.

Can you try this out already and let me know what you think about it?

thanks
erwin

**Comment by erwindl0** [comment]
PR #207 contributes what I would propose as currently sufficient fix for this issue. Review/feedback is very welcome!

Not sure what's the right way to comment on remaining issues : in the PR and/or this issue, so I copy some info here from the PR  #207 : 

Known remaining issues depend on EMF Forms limitations. I would prefer to handle them in separate future issues :
- how to make some settings in a an actor's port table read-only for predefined ports (i.e. defined in the actor code) while allowing them to be edited for ports added via configuration? And similar how to prevent deletion of the predefined ports.
- using a combo box in the port table, for the Direction property

**Comment by cxbrooks** [comment]
This looks pretty good.  The enum problem is a bit annoying, I agree that handling it in a separate issue is fine, please go ahead and create them and then close this one.

On other minor issue is that if a port is both an input and an output, the icon should reflect that.  This is a minor issue, should I open a separate issue for it?

**Comment by erwindl0** [comment]
I'll use a shape similar to the one used in Ptolemy II for input/output.

**Comment by cxbrooks** [comment]
Ports that are both input and output are confusing and not often used in Ptolemy II, but now the Triquetrum editor supports them.
