### ISSUE TITLE
Error messages on startup

### ISSUE THREAD

**Issue by hugo-bluecorn** [eclipse/triquetrum#166]
Hi

I need help getting the workbench functionality working please.

I just downloaded  org.eclipse.triquetrum.workflow.editor.rcp.incubation-0.1.0-linux.gtk.x86_64.zip

I got the workbench to start but I do not see any of the triquetrum functionality available (views wizards perspective etc)

I have these error messages on startup which could be related.

hugo@linux-2hfm:~/bpm> ./eclipse 
!SESSION 2016-09-23 09:41:13.790 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_101
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_BE
Command-line arguments:  -os linux -ws gtk -arch x86_64 -consoleLog -console

!ENTRY org.eclipse.equinox.ds 1 0 2016-09-23 09:41:15.238
!MESSAGE Could not bind a reference of component TaskProcessingBroker. The reference is: Reference[name = TaskProcessingService, interface = org.eclipse.triquetrum.processing.service.TaskProcessingService, policy = dynamic, cardinality = 0..n, target = null, bind = registerServiceRef, unbind = removeServiceRef]
2016-09-23 09:41:15,401 INFO [Component Resolve Thread]  impl.WorkflowExecutionServiceImpl (<init>:53) - Creating WorkflowExecutionServiceImpl for 8 max concurrent processes

!ENTRY org.eclipse.equinox.ds 1 0 2016-09-23 09:41:15.441
!MESSAGE Could not bind a reference of component MomlParserClassLoadingStrategy. The reference is: Reference[name = ActorOrientedClassProvider, interface = org.ptolemy.classloading.ActorOrientedClassProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addActorOrientedClassProvider, unbind = removeActorOrientedClassProvider]
osgi> openjdk version "1.8.0_101"
OpenJDK Runtime Environment (IcedTea 3.1.0) (suse-1.3-x86_64)
OpenJDK 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by erwindl0** [comment]
Hi Hugo,

The errors are coming from the Equinox Declarative Services startup, as 
we've still got detailed logging activated.
But the DS service retries a couple of times and then finds the 
components. So this should not impact the workbench state after the full 
startup is finished.

For the moment we don't have a custom perspective yet. To get started, 
you just need to create a plain eclipse project in your workspace and 
then do a File > New > Other and select the Triquetrum entry in the 
Workflows section.

This is documented on https://wiki.eclipse.org/Triquetrum/Getting_Started

Can you try if that works for you? Let me know if there would still be 
an issue.

Remark that the actual actors available in the editor are still limited.
I have attached 2 sample workflows that you could copy in your project 
to play with (hope this gets attached correctly to the github issue, 
from a simple email reply)

regards
erwin

Op 9/23/2016 om 9:57 AM schreef Hugo A. Garcia:

**Comment by hugo-bluecorn** [comment]
Hi

Got the workspace working. thanks.

The example projects attachment did not work.

**Comment by erwindl0** [comment]
Hi Hugo,

I have attached a test project in a zip with the 2 simple sample flows.

[test.zip](https://github.com/eclipse/triquetrum/files/489650/test.zip)

let me know if that works.

thanks
erwin

**Comment by cxbrooks** [comment]
Maybe we should have a Welcome tab that states that we don't have a view or wizard?  See http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Fua_intro.htm  

I added text to https://wiki.eclipse.org/Triquetrum/Downloads about the missing perspective and views.  

We know we are missing the perspective, see Bug #160:
> 8 : there is no custom perspective yet

I'll try the test.zip file later.

**Comment by erwindl0** [comment]
Closing this as it was more a request-for-help and the welcome-page-issue will be provided from #169 

Hugo, if you think there's till something to be done here, pls reopen!
