### ISSUE TITLE
Reorg the repository into plugins/, features/, releng/ and other directories

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#170]
The top level directory of the repo is cluttered.  Perhaps we should create plugins/, features/, releng/ and other directories.

We would need to update the how Maven builds.

This should happen after the Science 2016 Release.

**Comment by erwindl0** [comment]
some inspiration can be found e.g. on http://www.vogella.com/tutorials/EclipseTycho/article.html#good-practice-for-eclipse-components-organization

**Comment by erwindl0** [comment]
subfolders created according to some examples I found.
the build works again.

can you review and close if OK?

**Comment by cxbrooks** [comment]
Thanks for doing this!  It looks pretty good.  I was able to check out a new tree and run mvn.

A couple of comments:

1. I think we lost the Welcome Window, see Bug #169 Create Welcome Window Support

2. After checking out a new tree and doing the setup by hand, in the Package Explorer, the various packages are displayed at the top level instead of in their folders:

<img width="421" alt="screen shot 2017-06-26 at 2 15 14 pm" src="https://user-images.githubusercontent.com/861991/27560695-015a7990-5a7a-11e7-99b5-af9cf60e6a6a.png">

However, the top level directory looks fine:

```
bash-3.2$ ls ~/git/triquetrum
CONTRIBUTING.md         README.md               javadoc                 releng                  tests
LICENSE                 examples                plugins                 setups
README-python-rpc.md    features                pom.xml                 target
bash-3.2$
```

Any ideas?

**Comment by erwindl0** [comment]
Christopher,

 

The welcome screen hasn’t worked yet for me, i.e. also not before the folder restructuring.

We need to check that topic separately I think.

 

The Eclipse Project explorer indeed does not show projects in subfolders, as far as I know.

We might define so-called “working sets” that correspond to folders, if you prefer.

(I think the Eclipse WTP project has hierarchical project views, but that’s for doing Java Enterprise dvp, not RCP)

 

Regards

erwin

**Comment by cxbrooks** [comment]
I'll reopen the Welcome Window bug.

Thanks for the info about the subfolders.

Let's close this.
