### ISSUE TITLE
RC1 Workflow Editor fails to start: DiagramEditorInput does not convey a Provider ID

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#185]
Under MacOS El Capitan, I downloaded
http://www.eclipse.org/downloads/download.php?file=/triquetrum/RC1/org.eclipse.triquetrum.workflow.editor.rcp.incubation-0.1.0RC1-macosx.cocoa.x86_64.zip&mirror_id=272

I created a new project, then a new workflow and then the workflow editor failed to open.  The error was:

> null argument:DiagramEditorInput does not convey a Provider ID 'org.eclipse.graphiti.ui.editor.DiagramEditorInput@21117cff uri: platform:/resource/myproj/workflows/newDiagram.tdml#/0. See the error log for details.

The Error log says that the stack is not available, but it does say:

> eclipse.buildId=unknown
> java.version=1.8.0_101
> java.vendor=Oracle Corporation
> BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
> Framework arguments:  -keyring /Users/cxh/.eclipse_keyring
> Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -consoleLog -console -keyring /Users/cxh/.eclipse_keyring
> 
> org.eclipse.ui
> Error
> Tue Oct 18 12:52:13 PDT 2016
> null argument:DiagramEditorInput does not convey a Provider ID 'org.eclipse.graphiti.ui.editor.DiagramEditorInput@21117cff uri: platform:/resource/myproj/workflows/newDiagram.tdml#/0. See the error log for details.

**Comment by cxbrooks** [comment]
The RC1 installer under 64-bit Linux does not have this problem, so it must be Mac-specific.

**Comment by erwindl0** [comment]
Also on Windows 64 this problem does not occur.

Davy tested on MacOS Sierra and did not have this issue neither.

Op 10/18/2016 om 10:19 PM schreef Christopher Brooks:

**Comment by cxbrooks** [comment]
I'm closing this.  The Eclipse installation from RC1 that I created yesterday still has the problem, but starting over with unzipping in a new directory seems to work.

I've included a diff of the not working version (Eclipse.app) and the working version (Eclipse 2.app)

I suspect a timing bug somewhere.
[TriqRC1Mac.diff.zip](https://github.com/eclipse/triquetrum/files/540401/TriqRC1Mac.diff.zip)

**Comment by cxbrooks** [comment]
I suspect that message

null argument:DiagramEditorInput does not convey a Provider ID 

appears if during the creation of a Triquetrum Workflow Model, the New Diagram dialog has a Diagram Type pull down that is empty instead of having "Triquetrum workflow" visible.

I saw this error when updating to Eclipse 2019-06 under JDK 1.8.

If I can replicate this reliably, I'll reopen this bug.
