### ISSUE TITLE
RC1 Mac Installer is from an unknown developer

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#186]
Under Mac OS, when I download http://www.eclipse.org/downloads/download.php?file=/triquetrum/RC1/org.eclipse.triquetrum.workflow.editor.rcp.incubation-0.1.0RC1-macosx.cocoa.x86_64.zip&mirror_id=272

and then unzip it and then click on Eclipse.app, I get a dialog about the app being from an unknown developer.

The workaround is to right click on Eclipse.app and select Open.

The fix to this is to make sure that we are signing Eclipse.app

The Windows version probably has a similar issue.

We could ship 0.0.1 without this being fixed.

**Comment by erwindl0** [comment]
(possibly also related to #188 ?)

There is some info and examples on signing applications during the build being discussed on cbi-dev : http://dev.eclipse.org/mhonarc/lists/cbi-dev/msg01776.html

There are win and mac signer plugins that can be configured in the pom.
It would seem this is something different from signing individual jars.

Info on those executables signing plugins : 
https://www.eclipse.org/cbi/sitedocs/eclipse-winsigner-plugin/plugin-info.html
https://www.eclipse.org/cbi/sitedocs/eclipse-macsigner-plugin/plugin-info.html

And on CBI in general : 
http://www.eclipse.org/community/eclipse_newsletter/2013/august/article3.php

**Comment by cxbrooks** [comment]
I've fixed this.  The key thing was to in org.eclipse.terraswarm.triquetrum.repository/pom.xml to move the archive-product goal into the pre-integration-phase so that the signing can occur before zipping.

```
                        <plugin>
                                <groupId>org.eclipse.tycho</groupId>
                                <artifactId>tycho-p2-director-plugin</artifactId>
                                <version>${tycho-version}</version>
                                <executions>
                                        <execution>
                                                <!-- (optional) install the product for all configured os/ws/arch environments                                             
                                                        using p2 director -->
                                                <id>materialize-products</id>
                                                <goals>
                                                        <goal>materialize-products</goal>
                                                </goals>
                                        </execution>
                                        <execution>
                                                <!-- (optional) create product zips (one per os/ws/arch) -->
                                                <id>archive-products</id>
                                                <goals>
                                                        <goal>archive-products</goal>
                                                </goals>
                                                <!-- We want to get the signing done before we archive, so we assign                                                       
                                                     the archive-products goal to the pre-integration-test.                                                                
                                                     See http://dev.eclipse.org/mhonarc/lists/cbi-dev/msg01777.html                                                        
                                                     -->                                                                                                                   
                                                <phase>pre-integration-test</phase>
                                        </execution>
                                </executions>
                        </plugin>
```

**Comment by cxbrooks** [comment]
It seems that the Mac installers in the Hudson are unsigned

I downloaded https://hudson.eclipse.org/triquetrum/job/triquetrum/lastSuccessfulBuild/artifact/org.eclipse.triquetrum.repository/target/products/org.eclipse.triquetrum.workflow.editor.rcp.incubation-0.2.0.qualifier-macosx.cocoa.x86_64.zip

<img width="417" alt="screen shot 2017-04-24 at 3 31 22 pm" src="https://cloud.githubusercontent.com/assets/861991/25361487/375bd596-2903-11e7-8b2d-9ab24f69cdb7.png">

Which says:

```
"triquetrum-0.2.0-SNAPSHOT 2" can't be
opened because it is from an unidentified
developer.

Your security preferences allow installations of
only apps from the App Store and identified developers.

Firefox downloaded this file today at 3:29 PM from
hudson.eclipse.org
```

**Comment by cxbrooks** [comment]
Fixed.  A key part of the fix was to use the same profile name for both signing the jars and signing the apps.

I verified that the Mac and x86_64 files from https://hudson.eclipse.org/triquetrum/job/triquetrum/180/artifact/org.eclipse.triquetrum.repository/target/products/ work without an unsigned application warning.
