### ISSUE TITLE
RC1 Linux 64 zip file should create a directory

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#187]
http://www.eclipse.org/downloads/download.php?file=/triquetrum/RC1/org.eclipse.triquetrum.workflow.editor.rcp.incubation-0.1.0RC1-linux.gtk.x86_64.zip

should be in a directory like triquetrum-0.1.0RC1/

What we have now is:

```
cxh@swarmnuc1017:~/Downloads/triq/tmp$ ls
org.eclipse.triquetrum.workflow.editor.rcp.incubation-0.1.0RC1-linux.gtk.x86_64.zip
cxh@swarmnuc1017:~/Downloads/triq/tmp$ unzip org.eclipse.triquetrum.workflow.editor.rcp.incubation-0.1.0RC1-linux.gtk.x86_64.zip 
Archive:  org.eclipse.triquetrum.workflow.editor.rcp.incubation-0.1.0RC1-linux.gtk.x86_64.zip
   creating: p2/
   creating: p2/org.eclipse.equinox.p2.engine/
   creating: p2/org.eclipse.equinox.p2.engine/profileRegistry/
   creating: p2/org.eclipse.equinox.p2.engine/profileRegistry/DefaultProfile.profile/
...
cxh@swarmnuc1017:~/Downloads/triq/tmp$ ls
artifacts.xml  eclipse      epl-v10.html  notice.html                                                                          p2       readme
configuration  eclipse.ini  features      org.eclipse.triquetrum.workflow.editor.rcp.incubation-0.1.0RC1-linux.gtk.x86_64.zip  plugins
```

What I would expect is that the zip file would first create a subdirectory named triquetrum-0.1.0RC1.

**Comment by erwindl0** [comment]
I see that an Eclipse Neon zip indeed has an eclipse folder in it.

But e.g. an ICE zip also has its contents without a parent folder.


Op 10/18/2016 om 10:18 PM schreef Christopher Brooks:

**Comment by cxbrooks** [comment]
See https://eclipse.org/tycho/sitedocs/tycho-p2/tycho-p2-director-plugin/archive-products-mojo.html

**Comment by cxbrooks** [comment]
Fixed!  Closing.
