### ISSUE TITLE
Provide an Oomph setup for a Triquetrum developer

### ISSUE THREAD

**Issue by erwindl0** [eclipse/triquetrum#211]
Eclipse Oomph allows to define a setup for an Eclipse IDE + a predefined workspace materialization.

The approach is to download the generic Eclipse Installer and then point to our setup file to obtain a ready-for-use Triquetrum development setup.
It would be handy for new Triquetrum developers/contributors to have such a "Triquetrum development" Oomph setup available.

For the moment, this would be about using an Eclipse Neon RCP/RAP IDE + a Triquetrum workspace configured on our current target platform (Oxygen).
Once Oxygen is released incl Oomph, we could switch the Eclipse IDE to Oxygen as well.

**Comment by erwindl0** [comment]
Added description on how to use the Oomph setup in our CONTRIBUTING.md and on the [Triquetrum wiki](https://wiki.eclipse.org/Triquetrum/Building_From_Sources#Using_the_Triquetrum_development_Oomph_setup).

**Comment by cxbrooks** [comment]
The Oomph setup is pretty slick!  I updated the wiki.

One issue is that if for Product Version, I select Latest (Oxygen), then a dialog appears that states:

The URI ' https://raw.githubusercontent.com/eclipse/triquetrum/master/setups/org.eclipse.triquetrum.developer.setup/TriquetrumDevelopment.setup' does not contain a valid product.

See the screenshot below:

<img width="820" alt="screen shot 2017-03-27 at 10 35 59 am" src="https://cloud.githubusercontent.com/assets/861991/24369643/81ea6b58-12d9-11e7-8ad4-154e317de941.png">

One slightly confusing thing is that if I keep the initial default Product Version of Latest Release (Neon), then when I start up Triquetrum, the Oxygen splash screen is displayed.  I feel this is correct, but what is possibly slightly confusing to a new user is that they are using Neon to build an Oxygen Triquetrum.  This is not a problem, just possibly confusing.

**Comment by cxbrooks** [comment]
Updated the wiki about selecting Oxygen.  Closing!

**Comment by cxbrooks** [comment]
During installation, I get a message about Unsigned Content:

/Users/cxh/.p2/pool/features/fr.obeo.releng.targetplatform-feature_2.1.1.201410251450

<img width="597" alt="screen shot 2017-03-27 at 1 09 07 pm" src="https://cloud.githubusercontent.com/assets/861991/24375837/a7efcd1a-12ee-11e7-84b0-d8df8ce74a80.png">

Probably to replicate this, it is necessary to remove the Eclipse Oomph installer directory and untar the distribution.

To close this, we should consider fixing the above.

Also, to close this, we should add Triquetrum to the list of available installations.

**Comment by cxbrooks** [comment]
I updated the documentation to include the Unsigned Content window.  It would be good to look into if we can find a signed version of these plugins or otherwise document the issue.

**Comment by erwindl0** [comment]
issue created on the targetplatform project : https://github.com/mbarbero/fr.obeo.releng.targetplatform/issues/70
