### ISSUE TITLE
Model with RecordDissassembler results in unreachable actors

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#219]
If a Triquetrum model has an RecordDissassembler in it, then the downstream actors are unreachable.

This model has a Const with a value {RData=42} connected to a RecordDisassembler connected to a Display:

[ConstRecordDisassemblerDisplay.tdml.zip](https://github.com/eclipse/triquetrum/files/947681/ConstRecordDisassemblerDisplay.tdml.zip)

When I run it, the following output appears in the console:

> 2017-04-21 09:26:04,814 WARN [pool-1-thread-3]  executor.WorkflowExecutionTask (executionError:226) - Context 187aa650-363a-45f9-893f-d8a12df54635 - Execution error of model newDiagram
> ptolemy.actor.sched.NotSchedulableException: SDF scheduler found disconnected actors! Usually, disconnected actors in an SDF model indicates an error.  If this is not an error, try setting the SDFDirector parameter allowDisconnectedGraphs to true.
> Unreached Actors:
> .newDiagram.Display 
> Reached Actors:
> .newDiagram.Constant .newDiagram.RecordDisassembler 
>   in .newDiagram.SDF director.Scheduler
> 	at ptolemy.domains.sdf.kernel.SDFScheduler._solveBalanceEquations(SDFScheduler.java:856)
> 	at ptolemy.domains.sdf.kernel.SDFScheduler._getSchedule(SDFScheduler.java:564)
> 	at ptolemy.actor.sched.Scheduler.getSchedule(Scheduler.java:189)
> 	at ptolemy.domains.sdf.kernel.SDFDirector.createSchedule(SDFDirector.java:408)
> 	at ptolemy.domains.sdf.kernel.SDFDirector.preinitialize(SDFDirector.java:765)
> 	at ptolemy.actor.CompositeActor.preinitialize(CompositeActor.java:1820)
> 	at ptolemy.actor.Manager.preinitializeAndResolveTypes(Manager.java:1030)
> 	at ptolemy.actor.Manager.initialize(Manager.java:702)
> 	at ptolemy.actor.Manager.execute(Manager.java:354)
> 	at org.eclipse.triquetrum.workflow.execution.impl.executor.WorkflowExecutionTask.call(WorkflowExecutionTask.java:121)
> 	at org.eclipse.triquetrum.workflow.execution.impl.executor.WorkflowExecutionTask.call(WorkflowExecutionTask.java:1)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)

For reference, here is the corresponding Ptolemy model:

[ConstRecordDisassemblerDisplay.xml.zip](https://github.com/eclipse/triquetrum/files/947689/ConstRecordDisassemblerDisplay.xml.zip)

**Comment by erwindl0** [comment]
I've imported the attached model and it works fine. 
The issue seems to be happening in an unpredictable manner.

In a longer model editing session, including moving relation endpoints to other ports/actors, I also had this error a couple of times.

Needs more testing&debugging to figure out under which exact conditions this occurs.

**Comment by erwindl0** [comment]
I think I have found the issue and fixed it.

Can you retest? would be nice to close 2 bugs for our call tomorrow ;-)

**Comment by cxbrooks** [comment]
Fixed!
