### ISSUE TITLE
Parameter names are not updated in the model

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#221]
If  I drag in a Parameter, click on configure and change the name to "myParameter", then the parameter name on the canvas is not updated, even after reloading the file.
Note that the tool tip has the correct parameter name:

<img width="292" alt="screen shot 2017-04-21 at 11 45 33 am" src="https://cloud.githubusercontent.com/assets/861991/25291741/294e5b36-2688-11e7-8959-d7b92c65c86a.png">

I would expect the canvas to say "myParameter:" where it says "Parameter:"

However, the tdml file 
[ParameterNotUpdated.tdml.zip](https://github.com/eclipse/triquetrum/files/948041/ParameterNotUpdated.tdml.zip)

has the correct parameter name:

```
<attributes xsi:type="org.eclipse.triquetrum.workflow:Parameter" name="myParameter" wrappedType="ptolemy.data.expr.Parameter" deepComplete="true" expression=""/>
```

Although earlier in the tdml file we have:

```
      <children visible="true">
        <properties key="__BO_CATEGORY" value="Parameter"/>
        <properties key="__BO_NAME" value="Parameter"/>
        <properties key="__BO_CLASS" value="org.eclipse.triquetrum.workflow.model.impl.ParameterImpl"/>
        <properties key="__BO_VALUE" value=""/>
        <graphicsAlgorithm xsi:type="al:Text" foreground="/0/@colors.3" lineWidth="1" filled="false" transparency="0.0" width="160" height="20" x="10" font="/0/@f\
onts.0" value="Parameter : "/>
        <link businessObjects="/1/@attributes.0"/>
      </children>
```

**Comment by erwindl0** [comment]
Christopher, can you retest before our call tomorrow?

thanks!

**Comment by cxbrooks** [comment]
Fixed!
