### ISSUE TITLE
The delete actor dialog should be optional

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#222]
When I delete an actor, I'm prompted with a window that asks me if I want to delete that actor.

<img width="514" alt="screen shot 2017-04-21 at 11 51 49 am" src="https://cloud.githubusercontent.com/assets/861991/25291948/f36eb6e0-2688-11e7-8196-6776490322eb.png">

Ideally, that window would have a "Please don't show me this type of window again." check box.  Or, there would be a way to disable it.

This is very low priority.

**Comment by erwindl0** [comment]
This is coming from Graphiti's DeleteAction implementation. 
I'll check if it can be adapted.

**Comment by erwindl0** [comment]
Done. The "remember my choice" choice is linked to an editor preference that can also be (un)set in a Triquetrum preference page now.

**Comment by cxbrooks** [comment]
Thanks!  I've confirmed that this works.
