### ISSUE TITLE
It should be possible to draw relations from input to output

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#223]
It seems that it is not possible to draw a connection from the input of an actor to the output of an actor.

For example, if a model has two actors, a Ramp and a Display, it is not possible to mouse on the input of the Display and drag the connection to the output of the Ramp.

This is a low priority task.

**Comment by erwindl0** [comment]
Indeed. I thought this would be ok good to start a connection in the right "direction", i.e. from output to input. If that's not desirable, I can look at changing that.

**Comment by erwindl0** [comment]
Should be resolved now, can you test it out?

**Comment by cxbrooks** [comment]
Thanks, this is fixed, I can draw relations from the input to the output.
