### ISSUE TITLE
Update Triquetrum Eclipse Oomph setup for Oxygen

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#234]
Eclipse Oxygen is getting close, we should get the installer updated.

I downloaded the Oxygen RC2 installer from https://www.eclipse.org/downloads/index-developer.php and followed the instructions in http://wiki.eclipse.org/Triquetrum/Building_From_Sources which clearly state to select Neon.

See also Bug #211: Provide an Oomph setup for a Triquetrum developer

However, as a test, I selected Oxygen and the following error occurred:

> Fetching p2.index from http://download.eclipse.org/releases/oxygen/201706021000/
> Fetching content.xml.xz from http://download.eclipse.org/releases/oxygen/201706021000/ (850.62kB)
> Calculating requirements and dependencies.
> Cannot complete the request.  Generating details.
> ERROR: org.eclipse.equinox.p2.director code=10054 Cannot complete the install because of a conflicting dependency.
>   at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:280)
>   at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.resolve(ProfileTransactionImpl.java:425)
>   at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:337)
>   at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:729)
>   at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3324)
>   at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3252)
>   at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3233)
>   at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3133)
>   at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:567)
>   at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:693)
>   at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
>   ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1496450899310
>   ERROR: org.eclipse.equinox.p2.director code=1 Only one of the following can be installed at once: 
>     ERROR: org.eclipse.equinox.p2.director code=0 Eclipse Workbench Model 1.2.0.v20160229-1459 (org.eclipse.e4.ui.model.workbench 1.2.0.v20160229-1459)
>     ERROR: org.eclipse.equinox.p2.director code=0 Eclipse Workbench Model 2.0.0.v20170228-1842 (org.eclipse.e4.ui.model.workbench 2.0.0.v20170228-1842)
>   ERROR: org.eclipse.equinox.p2.director code=1 Only one of the following can be installed at once: 
>     ERROR: org.eclipse.equinox.p2.director code=0 Edit SWT 1.11.0.20161205-1431 (org.eclipse.emf.ecp.edit.swt 1.11.0.20161205-1431)
>     ERROR: org.eclipse.equinox.p2.director code=0 Edit SWT 1.12.0.20170314-0912 (org.eclipse.emf.ecp.edit.swt 1.12.0.20170314-0912)
>     ERROR: org.eclipse.equinox.p2.director code=0 Edit SWT 1.13.0.20170522-1501 (org.eclipse.emf.ecp.edit.swt 1.13.0.20170522-1501)
>     ERROR: org.eclipse.equinox.p2.director code=0 Edit SWT 1.12.0.20170227-1527 (org.eclipse.emf.ecp.edit.swt 1.12.0.20170227-1527)
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1496450899310
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.emf.ecp.sdk.feature.feature.group 0.0.0
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1496450899310
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.emf.ecp.view.table.celleditor.rcp.feature.feature.group 0.0.0
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1496450899310
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.rcp.feature.group [4.7.0,4.8.0)
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: Eclipse 4 Rich Client Platform 1.6.0.v20170512-0445 (org.eclipse.e4.rcp.feature.group 1.6.0.v20170512-0445)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.e4.ui.model.workbench [2.0.0.v20170228-1842]
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: Eclipse 4 Rich Client Platform 1.6.0.v20170518-1424 (org.eclipse.e4.rcp.feature.group 1.6.0.v20170518-1424)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.e4.ui.model.workbench [2.0.0.v20170228-1842]
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: Eclipse 4 Rich Client Platform 1.6.0.v20170523-1901 (org.eclipse.e4.rcp.feature.group 1.6.0.v20170523-1901)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.e4.ui.model.workbench [2.0.0.v20170228-1842]
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: ECP e4 Application 1.11.0.20161205-1431 (org.eclipse.emf.ecp.application.e4 1.11.0.20161205-1431)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: bundle org.eclipse.e4.ui.model.workbench [0.10.0,2.0.0)
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: ECP e4 Demo Application 1.11.0.20161205-1431 (org.eclipse.emf.ecp.demo.e4.feature.feature.group 1.11.0.20161205-1431)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.emf.ecp.application.e4 [1.11.0.20161205-1431]
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: ECP 3.x UI Integration 1.12.0.20170227-1527 (org.eclipse.emf.ecp.e3.feature.feature.group 1.12.0.20170227-1527)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.emf.ecp.editor.e3 [1.12.0.20170227-1527]
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: ECP Editor integration for 3.x Workbench 1.12.0.20170227-1527 (org.eclipse.emf.ecp.editor.e3 1.12.0.20170227-1527)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: bundle org.eclipse.emf.ecp.edit.swt [1.12.0,1.13.0)
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: EMF Forms Runtime 1.12.0.20170314-0912 (org.eclipse.emf.ecp.emfforms.runtime.feature.feature.group 1.12.0.20170314-0912)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.emf.ecp.viewmodel.feature.feature.group [1.12.0.20170314-0912]
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: EMF Forms SDK 1.12.0.20170227-1527 (org.eclipse.emf.ecp.emfforms.sdk.feature.feature.group 1.12.0.20170227-1527)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.emf.ecp.e3.feature.feature.group [1.12.0.20170227-1527]
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: ECP Explorer Editor Bridge 1.13.0.20170522-1501 (org.eclipse.emf.ecp.explorereditorbridge 1.13.0.20170522-1501)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: bundle org.eclipse.emf.ecp.edit.swt [1.13.0,1.14.0)
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: ECP Core 1.13.0.20170522-1501 (org.eclipse.emf.ecp.feature.feature.group 1.13.0.20170522-1501)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.emf.ecp.explorereditorbridge [1.13.0.20170522-1501]
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: ECP SDK e4 (Target Feature) 1.11.0.20161205-1431 (org.eclipse.emf.ecp.sdk.e4.feature.feature.group 1.11.0.20161205-1431)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.emf.ecp.demo.e4.feature.feature.group [1.11.0.20161205-1431]
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: ECP SDK e4 (Target Feature) 1.12.0.20170314-0912 (org.eclipse.emf.ecp.sdk.e4.feature.feature.group 1.12.0.20170314-0912)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.emf.ecp.emfforms.runtime.feature.feature.group [1.12.0.20170314-0912]
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: ECP SDK e4 (Target Feature) 1.13.0.20170522-1501 (org.eclipse.emf.ecp.sdk.e4.feature.feature.group 1.13.0.20170522-1501)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.emf.ecp.feature.feature.group [1.13.0.20170522-1501]
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: ECP SDK 3.x 1.11.0.20161205-1431 (org.eclipse.emf.ecp.sdk.feature.feature.group 1.11.0.20161205-1431)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.emf.ecp.sdk.e4.feature.feature.group [1.11.0.20161205-1431]
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: ECP SDK 3.x 1.12.0.20170227-1527 (org.eclipse.emf.ecp.sdk.feature.feature.group 1.12.0.20170227-1527)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.emf.ecp.emfforms.sdk.feature.feature.group [1.12.0.20170227-1527]
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: ECP SDK 3.x 1.12.0.20170314-0912 (org.eclipse.emf.ecp.sdk.feature.feature.group 1.12.0.20170314-0912)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.emf.ecp.sdk.e4.feature.feature.group [1.12.0.20170314-0912]
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: ECP SDK 3.x 1.13.0.20170522-1501 (org.eclipse.emf.ecp.sdk.feature.feature.group 1.13.0.20170522-1501)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.emf.ecp.sdk.e4.feature.feature.group [1.13.0.20170522-1501]
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: Table UI SWT Additional Cell Editors for Non-RAP Applications 1.11.0.20161205-1431 (org.eclipse.emf.ecp.view.table.celleditor.rcp 1.11.0.20161205-1431)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: bundle org.eclipse.emf.ecp.edit.swt [1.11.0,1.12.0)
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: EMFForms Table UI SWT Additional Cell Editors (non-RAP) 1.11.0.20161205-1431 (org.eclipse.emf.ecp.view.table.celleditor.rcp.feature.feature.group 1.11.0.20161205-1431)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.emf.ecp.view.table.celleditor.rcp [1.11.0.20161205-1431]
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: EMF Forms Core Model 1.12.0.20170314-0912 (org.eclipse.emf.ecp.viewmodel.feature.feature.group 1.12.0.20170314-0912)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.emf.ecp.edit.swt [1.12.0.20170314-0912]
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: Eclipse RCP 4.7.0.v20170512-0500 (org.eclipse.rcp.feature.group 4.7.0.v20170512-0500)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.e4.rcp.feature.group [1.6.0.v20170512-0445]
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: Eclipse RCP 4.7.0.v20170518-1424 (org.eclipse.rcp.feature.group 4.7.0.v20170518-1424)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.e4.rcp.feature.group [1.6.0.v20170518-1424]
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: Eclipse RCP 4.7.0.v20170524-2000 (org.eclipse.rcp.feature.group 4.7.0.v20170524-2000)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.e4.rcp.feature.group [1.6.0.v20170523-1901]
> 
> Took 8 seconds.
> There are failed tasks.
> Press Back to choose different settings or Cancel to abort.

This is not a big deal because we say to use Neon, but we should update https://raw.githubusercontent.com/eclipse/triquetrum/master/setups/org.eclipse.triquetrum.developer.setup/TriquetrumDevelopment.setup to work with Oxygen.

**Comment by erwindl0** [comment]
Christopher,

Setup is on Oxygen release now. 
Can you review and close if OK?

**Comment by cxbrooks** [comment]
Hmm, this is not working for me.  I'm following https://wiki.eclipse.org/Triquetrum/Building_From_Sources
When I get to step 4: "Click on the green plus (+) sign...",  I get the following when I paste in the URL:

The URI 'https://raw.githubusercontent.com/eclipse/triquetrum/master/setups/org.eclipse.triquetrum.developer.setup/TriquetrumDevelopment.setup' does not contain a valid product.

<img width="815" alt="screen shot 2017-07-23 at 4 07 01 pm" src="https://user-images.githubusercontent.com/861991/28502468-16a0c49c-6fc1-11e7-9644-f2f4b6d7967e.png">

I'll take another look tomorrow.

**Comment by cxbrooks** [comment]
I'm closing this because it works.  My error was that I clicked the + in the Product page instead of the Projects page.
