### ISSUE TITLE
File -> Open File... does not add a file to a project

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#238]
If I do File -> Open File... and open a .tdml file, then the file opens, but is not added under the project.

To replicate:
1. Download the ICEdemo1.zip file from https://wiki.eclipse.org/File:ICEdemo1.zip
2. In Triquetrum, in the Project Explorer, right click, select New Project -> General -> Project, click on Next, enter a project name click on Finish
3. With the newly created project highlighted, select File -> Open File ... and browse to the ICEDemo1.tdml file.  Click Open
4. The .tdml file will open, but is not added under the project.

See https://wiki.eclipse.org/Triquetrum/Opening_A_Model for screenshots

See also bug #65 File->Open should be able to open a .tdml file

**Comment by erwindl0** [comment]
This is expected behavior for the File -> Open File… menu item in Eclipse.

Its purpose is to be able to open/edit files that are not in your workspace.

 

The behavior you would like is in the File -> Import menu item.

 

So I would prefer to stick to the general behavior/expectations of those 2 actions.

**Comment by cxbrooks** [comment]
Right, thanks for reminding me that File -> Open File ... should open a file outside of the project.

I had tried right clicking on the project and selecting import and under Triquetrum. There is a "Ptolemy II MoML File" choice, but there is no tdml choice?

**Comment by erwindl0** [comment]
That’s a good remark 😉

 

You can just drag-n-drop into your Eclipse project or use Import -> General > Filesystem and then select the file and the desired import location in your workspace/project.

As we need no “processing” for a tdml file, only a plain copy, that is sufficient.

 

But we may add an explicit import type under triquetrum for tdml as well, that does the plain copy.

**Comment by cxbrooks** [comment]
Ok, I'm closing this.  The issue was that I did not understand how this was supposed to work.  I updated https://wiki.eclipse.org/Triquetrum/Opening_A_Model and created https://wiki.eclipse.org/Triquetrum/Importing_A_Model
