### ISSUE TITLE
Triquetrum Eclipse installer: Error Adding Products

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#252]
When following https://wiki.eclipse.org/Triquetrum/Building_From_Sources, I get to step 4:

> 4. Click on the green plus (+) sign to the right of the entry widget at top. The Add User Projects window will appear. In that window, in the Resource URIs field, enter the URL of the setup file:
> 
>  https://raw.githubusercontent.com/eclipse/triquetrum/master/setups/org.eclipse.triquetrum.developer.setup/TriquetrumDevelopment.setup
> 
> Click on OK. (TODO : we need to add our setup to the standard list at Eclipse).

Unfortunately, I get a failure:  

> The URI 'https://raw.githubusercontent.com/eclipse/triquetrum/master/setups/org.eclipse.triquetrum.developer.setup/TriquetrumDevelopment.setup'
> does not contain a valid product.

See below:

<img width="818" alt="screen shot 2017-06-26 at 1 30 34 pm" src="https://user-images.githubusercontent.com/861991/27559041-fdb84c32-5a73-11e7-8111-4ed3a0bdcb18.png">

**Comment by cxbrooks** [comment]
The installation continues, probably because I've done it before.

Later, I get

> One modeling project is invalid.
> Zero representations file found in "org.eclipse.triquetrum.workflow.model". A modeling project must contain one.

**Comment by erwindl0** [comment]
The setup works for me (cfr also update on #234 ).

But I notice from your screenshot that you seem to have an outdated installer version (1.6.0 Build 2790) and selected Neon as product version.

Can you update your installer to the Oxygen version and also switch to Oxygen as selected product version for the Triquetrum setup?

**Comment by cxbrooks** [comment]
I'm closing this one because the problem was that I clicked on the green plus when in the Product page, not the Projects page.  I updated https://wiki.eclipse.org/Triquetrum/Building_From_Sources to mention this issue and refer to this bug.
