### ISSUE TITLE
Release Triquetrum 0.2.0

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#281]
Now that we have approval, to finish the release, we need to:

- [x] Build installers 
- [x] Update https://github.com/eclipse/triquetrum/releases
- [x] Update https://projects.eclipse.org/projects/science.triquetrum/downloads
- [x] Update https://wiki.eclipse.org/Triquetrum/Downloads
- [x] Update the version from 0.2.0 to 0.2.1

**Comment by cxbrooks** [comment]
Ok, I've created 0.2.0rc1 prebuilt distributions at http://download.eclipse.org/triquetrum/0.2.0RC1/?d

My notes are at https://wiki.eclipse.org/Triquetrum/Releng/Milestone_Builds

I tested the Mac, 64-bit Linux and 64-bit Windows prebuilt binaries and created some issues.

The next steps are to decide what we are going to fix and to then modify Hudson to create the final versions.

**Comment by erwindl0** [comment]
Thanks Christopher to prepare all of this. I’ll look at things later today to see what should be addressed still.

**Comment by erwindl0** [comment]
There's a build issue for the signing step. 

Still some references to SNAPSHOT in releng/...repository/pom.xml.
I'll remove them.

**Comment by cxbrooks** [comment]
I built new binaries, they are at http://download.eclipse.org/triquetrum/0.2.0/?d

I noticed that the Mac app is not signed, I'm looking at

https://wiki.eclipse.org/IT_Infrastructure_Doc#Sign_my_plugins.2FZIP_files.3F and https://www.eclipse.org/cbi/sitedocs/eclipse-macsigner-plugin/plugin-info.html

It looks like Ice had to do something similar, see https://dev.eclipse.org/mhonarc/lists/cbi-dev/msg01632.html

**Comment by erwindl0** [comment]
The release has been defined on Github, download info has been updated on the wiki.
Installers(zips) are available from the download links.

So I think we're all set.

Remark that I would like to plan a 0.2.1 before the end of the year, with some small fixes/enhancements.
So we should not yet go for 0.3.0 now.

**Comment by erwindl0** [comment]
I've tried version updates limited to modules that are impacted by changes. (cfr #291 )
This is more aligned with semantic versioning (although there's a lot more needed to be clean on that level), than updating all versions in bulk.
