### ISSUE TITLE
Copying an actor does not copy its icon

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#289]
In Triquetrum 0.2.0RC1, when I drag in an actor that has a custom icon and then copy and paste it, the new actor does not have the custom icon.

**Comment by erwindl0** [comment]
working on this, fix should be available today.

**Comment by erwindl0** [comment]
christopher, can you check that this fixes the icon copy issue?

**Comment by cxbrooks** [comment]
This is fixed in the master tree.  I'll check it when we create another release candidate.
Closing...
