### ISSUE TITLE
0.2.0RC1 Win64 binary unzip problem: Path too long

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#292]
While unzipping the Win 64 zip at  http://download.eclipse.org/triquetrum/0.2.0RC1/org.eclipse.triquetrum.workflow.editor.rcp.incubation-0.2.0-win32.win32.x86_64.zip a message about 

```
1 Interrupted Action
An unexpected error is keeping you from copying the file. If you continue
to receive this error, you can use the error code to search for help with this
problem

Error: 0x80010135: Path too long

org.eclipse.equinox.p2.metadata.repository.prefs
Type: PREFS File
Date modified: 10/7/2017 4:41 PM
Size: 282 bytes
```

<img width="435" alt="screen shot 2017-10-07 at 2 33 55 pm" src="https://user-images.githubusercontent.com/861991/31312111-f0090aac-ab6f-11e7-82f8-b42037c073f4.png">

Clicking Skip results in some other, similar dialogs popping up.

https://www.ibm.com/support/knowledgecenter/en/SSFUEU_7.0.0/com.ibm.swg.ba.cognos.Installation_Guide_WebSphere.7.0.0.doc/c_in_trbls_uncompress_camphor.html suggests using 7zip

**Comment by cxbrooks** [comment]
This is a known misfeature of Windows.

This issue occurred under Windows Server 2012 R2, which is similar to Windows 8.

The workaround is to use 7-zip, as documented in https://wiki.eclipse.org/Triquetrum/Downloads#Windows:_Unzip_problem:_Path_too_long

**Comment by abdulqatari** [comment]
Don't get panic. Just download Long path tool. It will help you to solve this problem.
