### ISSUE TITLE
Update to Eclipse 2019-06 and Java 12

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#311]
Triquetrum should be updated to Eclipse 2019-06 and Java 12.  See https://wiki.eclipse.org/Triquetrum/Releng/New_Eclipse_Version

**Comment by cxbrooks** [comment]
I have notes at https://wiki.eecs.berkeley.edu/ptexternal/Main/Triq2019

One thing that should be looked at is that PaletteConfigurationElement.java in o.e.t.workflow.editor extends IConfigurationElement which now has a getHandleId method that needs to be extended.

My temporary workaround is to have getHandleId() throw an UnsupportedOperationException.  I think this is correct because many other methods throw the same exception, but it should probably be reviewed.

**Comment by erwindl0** [comment]
Throwing an exception might be tricky, as the IConfigurationElement.equals() seems to refer to the handle ID.

Cfr https://help.eclipse.org/2019-03/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fcore%2Fruntime%2FIConfigurationElement.html&anchor=equals(java.lang.Object)

I don't really know what the handle ID really stands for, but I guess we could try to return the hash code of the name or something similar i.o. throwing an exception.

**Comment by cxbrooks** [comment]
After the CI build at https://ci.eclipse.org/triquetrum/job/triquetrum/ finishes and the executable is tested, then this issue may be closed.

**Comment by cxbrooks** [comment]
Triquetrum now uses Eclipse 2019-09 and is JDK-13 compatible.

Closing...
