### ISSUE TITLE
Update to EPL-2.0

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#313]
Should we update the about.html files to EPL-2.0?

https://www.eclipse.org/legal/epl-2.0/

**Comment by cxbrooks** [comment]
I updated the contents of the top level LICENSE file from https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.txt, which I found via the right menu on https://www.eclipse.org/legal/legalfaq.php

I updated the about.html files from https://www.eclipse.org/legal/epl/epl-2.0/about.html, which I found via https://www.eclipse.org/legal/epl/about.php.  To determine the about.html files to be updated, I checked out the triquetrum repo, then used find.  I then used sum to verify that all the about.html files were the same - that there were no dual licensed about.html files.

One remaining issue is that a number of the Java files have headers that refer to EPL-1.0:

For example: triquetrum/plugins/core/org.eclipse.triquetrum.processing.model.impl/src/main/java/\
org/eclipse/triquetrum/processing/model/impl/TriqFactoryImpl.java contains:

```
/*******************************************************************************                               
 * Copyright (c) 2015, 2016 iSencia Belgium NV.                                                                
 * All rights reserved. This program and the accompanying materials                                            
 * are made available under the terms of the Eclipse Public License v1.0                                       
 * which accompanies this distribution, and is available at                                                    
 * http://www.eclipse.org/legal/epl-v10.html                                                                   
 *                                                                                                             
 * Contributors:                                                                                               
 *    Erwin De Ley - initial API and implementation and/or initial documentation                               
 *******************************************************************************/
```

To update the license to EPL-2.0, Erwin would need to agree or to do the update.  

If the file license is changed, then year should probably be updated to 2019.

There is information about the copyright headers at https://www.eclipse.org/projects/handbook/#ip-copyright-headers

**Comment by erwindl0** [comment]
I think indeed that we need to do that.

I can do that with a bulk change this evening.

**Comment by erwindl0** [comment]
In the different *.feature projects, it appears the license info is in license.html files.
+ there are separate epl-v10.html files as well in them.

The legal info page on feature contents (cfr paragraph 4 in https://www.eclipse.org/legal/guidetolegaldoc2.php), seems to be out-of-date for EPL 2...

**Comment by cxbrooks** [comment]
Thanks, good catch, I'll update those after you make your changes.

**Comment by erwindl0** [comment]
found a tool WTP releng which has a function to update feature license info to use "shared licenses"

Cfr eg https://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Ftasks%2Fpde_shared_license.htm

But now I need to figure out what this org.eclipse.license thing is and how to get it in the build

**Comment by erwindl0** [comment]
damn, the p2 repo they list seems to contain nothing...

will continue tomorrow...

**Comment by cxbrooks** [comment]
Done.  Many thanks to Erwin.

Closing.
