### ISSUE TITLE
Dual License Triquetrum under EPLv1.0 and EPL-1.0-BSD

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#46]
The University of California (UC) has a problem with the patent clause in EPL.  The concern is that if a UC employee (someone who has signed the UC patent agreement, which includes funded students) unknowingly contribute software that is covered by a patent held elsewhere in the UC system, then there is a conflict.  One workaround is to have UC contributors sign an individual contributor agreement.

Jay pointed out that there is the possibility of dual licensing Triquetrum as other projects have proposed doing and presumably done so.

https://projects.eclipse.org/proposals/eclipse-advanced-visualization-project  says:

> Licenses: 
> Eclipse Distribution License 1.0 (BSD)
> Eclipse Public License 1.0
>
> Legal Issues: 
>
> As far as the proposers know, no one owns the trademark to the project name.
>
> Many, if not all, of the third-party dependencies in the initial contribution have already received
> preliminary approval in Contribution Questionnaires (CQs) filed by existing Eclipse projects.

> We have selected both EDL and EPL for licenses because technology such this will most likely be in
> demand by many scientific institutions, some of which may not want to use it under the terms of the
> EPL. The project lead is willing to provide a justification letter for the IP-Team, Executive Director and
> the Board if required. For its part of the initial contribution, Oak Ridge National Laboratory/UT-Battelle,
> LLC approves of the dual licensing.

The EDL-1.0-BSD at https://www.eclipse.org/org/documents/edl-v10.php states:
> Eclipse Distribution License - v 1.0
>
> Copyright (c) 2007, Eclipse Foundation, Inc. and its licensors.
>
> All rights reserved.
>
> Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
>
>     Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
>     Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
>     Neither the name of the Eclipse Foundation, Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission. 
>
> THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

To close this bug, we need to:

1) Get the OK to use both licenses
2) Define what text goes in to files
3) Update the license files.

For 1) Get the OK to use both licenses, https://eclipse.org/legal/ says:
> Eclipse Distribution License (EDL): The BSD license used by some Eclipse projects which require 
> dual-licensing along with the EPL. Other than for example code or build scipts, use of this license by
> an Eclipse project is on a case-by-case basis and requires unanimous approval of the Board of 
> Directors. 

For 2) Define what text goes in to files
Some guidance may be found at https://eclipse.org/legal/eplfaq.php#DUALLIC:
> For Eclipse projects which are dual-licensed, your file headers state that the code is being made 
> available under two licenses. For example: "This program and the accompanying materials are made 
> available under the terms of the Eclipse Public License v1.0 and Eclipse Distribution License v. 1.0 
> which accompanies this distribution." What is meant by the use of the conjunction "and"?
> The code is being made available under both of the licenses. The consumer of the code can select 
> which license terms they wish to use, modify and/or further distribute the code under. 

For 3) Update the license files, this can be done if and when 1 and 2 are done.

**Comment by jayjaybillings** [comment]
We need to talk to @waynebeaton about this. You should email this thread to emo@eclipse.org (which just goes to Wayne).

**Comment by mmilinkov** [comment]
I do not see how dual-licensing the project solves UC's concerns. Dual-licensing means that the contributions would come in under *both* licenses, and the patent grants in the EPL would still apply.

To me the simplest solution is in your first paragraph: UC committers should sign the individual committer agreements. In fact, as far as I know UC is not a member of the Eclipse Foundation, so that is what UC committers would have to do in any event.

**Comment by jayjaybillings** [comment]
I think I misunderstood the issue that UC has with the EPL. At least in previous discussions with them (for ICE) they refused to allow LBNL employees to create projects and release them under the EPL, but they were free to contribute to them subject to the ICA. 

I was also thinking about this from the standpoint of other Berkeley projects using Triquetrum and refusing to do so because of the EPL and UC's complaints against it. This was the big reason we requested dual licensing for EAVP: there are significant community projects who won't use it under the EPL.

So, I may have raised the idea of dual licensing without fully understanding the problem and for that I apologize. I think Mike is right that dual licensing doesn't solve the contribution problem.

**Comment by cxbrooks** [comment]
It seems that dual licensing will not solve UC's problem with the EPL.

Some projects at Berkeley were able to use the [Educational Community License, Version 2.0 (ECL-2.0)] 
(https://opensource.org/licenses/ECL-2.0), which says:
> "The Educational Community License version 2.0 ("ECL") consists of the Apache 2.0 license, modified to change the scope of the patent grant in section 3 to be specific to the needs of the education communities using this license. The original Apache 2.0 license can be found at: http://www.apache.org/licenses/LICENSE-2.0"

Section 3 is:
> "3. Grant of Patent License.
> "Subject to the terms and conditions of this License, each Contributor hereby grants to You a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable (except as stated in this section) patent license to make, have made, use, offer to sell, sell, import, and otherwise transfer the Work, where such license applies only to those patent claims licensable by such Contributor that are necessarily infringed by their Contribution(s) alone or by combination of their Contribution(s) with the Work to which such Contribution(s) was submitted. If You institute patent litigation against any entity (including a cross-claim or counterclaim in a lawsuit) alleging that the Work or a Contribution incorporated within the Work constitutes direct or contributory patent infringement, then any patent licenses granted to You under this License for that Work shall terminate as of the date such litigation is filed. Any patent license granted hereby with respect to contributions by an individual employed by an institution or organization is limited to patent claims where the individual that is the author of the Work is also the inventor of the patent claims licensed, and where the organization or institution has the right to grant such license under applicable grant and research funding agreements. No other express or implied licenses are granted."

If the Eclipse Foundation and UC were able to agree on a similar license that was based on the EPL, then perhaps Triquetrum could have a single license, and organizations like UC Berkeley could join the Eclipse Foundation.  I realize that having Eclipse adopt a different license for some packages is not very practical and not very likely.  In addition, the patent clause in the EPL provides a modicum of protection for the users of the EPL-licensed software. Modifying the EPL to be like the ECL reduces that protection, which is also probably not palatable.

The downside is that UC won't agree to the the EPL as is, which means that UC cannot join the Eclipse Foundation.  This means that we are losing an opportunity to train students in how to directly collaborate as a part of their organization with the open source community.  Yes, UC students, staff and faculty may sign Individual Committer Agreements as a workaround, but we are missing out on an opportunity.

I don't think there is much else to be done here, so I'll close this issue in a few days if there is no further discussion.

**Comment by mmilinkov** [comment]
Christopher,

I believe I predicted that dual-licensing would not solve UC Berkley's concerns :)

Your post does not explain why having committers sign the Individual Committer Agreement would not suffice. Would you mind explaining that?

**Comment by cxbrooks** [comment]
Hi Mike,

I'm not that proud of UC Berkeley, but I am (mostly) proud of what what 
Berkeley has done with open source software.  I don't like denying that 
I work at UC Berkeley.

Once it became clear that I would need to sign an ICA if I wanted to 
contribute, it made it rather pointless for Berkeley to join the Eclipse 
Foundation.  I was told that it would be difficult for Berkeley to join 
with the EPL as is.  If Berkeley joined, it might increase student 
participation in Eclipse projects and teach students how to work on open 
source projects.

In a perfect world, students, staff and faculty at UC would be able to 
contribute without executing ICAs.

I don't agree with the guidelines from the UC Office of the President, 
so I'm not that comfortable defending them.

_Christopher


On 2/16/16 2:58 PM, Mike Milinkovich wrote:
>
> Christopher,
>
> I believe I predicted that dual-licensing would not solve UC Berkley's 
> concerns :)
>
> Your post does not explain why having committers sign the Individual 
> Committer Agreement would not suffice. Would you mind explaining that?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/eclipse/triquetrum/issues/46#issuecomment-184909839>.
>

-- 
Christopher Brooks, PMP                       University of California
Academic Program Manager & Software Engineer  US Mail: 337 Cory Hall
CHESS/iCyPhy/Ptolemy/TerraSwarm               Berkeley, CA 94720-1774
cxh@eecs.berkeley.edu, 707.332.0670           (Office: 545Q Cory)

**Comment by mmilinkov** [comment]
Christopher,

I wouldn't be too hard on UC Berkley or the UC Office of the President. I believe that they're just [following the law](https://en.wikipedia.org/wiki/Bayh%E2%80%93Dole_Act). 

It would be great if UC Berkley became a member, but the topic of this particular issue is dual-licensing Triquetrum. Could you clarify if the project itself is moving forward?

**Comment by cxbrooks** [comment]
Hi Mike,

Yes!  Triquetrum is proceeding!  We have nightly builds that include RCP 
installers.  I'm giving a talk at about Triquetrum at EclipseCon NA and 
submitted a poster for another conference in June.

The patent question is a mess.  I'm not sure how much more I want to go 
into it :-)  Maybe over beer.

Anyway, I'm not sure if I should follow up to epl-discuss@eclipse.org, I 
think we have answered this here.

_Christopher

On 2/17/16 7:53 AM, Mike Milinkovich wrote:
>
> Christopher,
>
> I wouldn't be too hard on UC Berkley or the UC Office of the 
> President. I believe that they're just following the law 
> <https://en.wikipedia.org/wiki/Bayh%E2%80%93Dole_Act>.
>
> It would be great if UC Berkley became a member, but the topic of this 
> particular issue is dual-licensing Triquetrum. Could you clarify if 
> the project itself is moving forward?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/eclipse/triquetrum/issues/46#issuecomment-185267711>.
>

-- 
Christopher Brooks, PMP                       University of California
Academic Program Manager & Software Engineer  US Mail: 337 Cory Hall
CHESS/iCyPhy/Ptolemy/TerraSwarm               Berkeley, CA 94720-1774
cxh@eecs.berkeley.edu, 707.332.0670           (Office: 545Q Cory)

**Comment by mmilinkov** [comment]
I agree. I think we're all done here, and I don't think that there is much interest at epl-discuss in weakening the patent licensing terms of the EPL. Although, one thing that could be interesting would be to find out if the UC Office of the President would be more comfortable with using patent non-assertion clauses, rather than patent licensing. (If you have no idea what that means, feel free to introduce me directly via email.)

We should definitely grab a beer at EclipseCon! Looking forward to meeting you there.

**Comment by cxbrooks** [comment]
I'm closing this.  The summary is that dual licensing will not help the UC lawyers.
