### ISSUE TITLE
File->Open should be able to open a .tdml file

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#65]
In Triquetrum, when I do File->Open and select a .tdml file, the following error message appears

> !ENTRY org.eclipse.ui 4 0 2016-03-05 08:44:25.250
> !MESSAGE Unknown editor input: org.eclipse.ui.ide.FileStoreEditorInput@6868b4a4

See https://wiki.eclipse.org/Triquetrum/Opening_A_Model for a workaround that involves dragging and dropping.

**Comment by cxbrooks** [comment]
Here's a zip of the .tdml file and data file.

[ICEdemo1.zip](https://github.com/eclipse/triquetrum/files/159937/ICEdemo1.zip)

**Comment by erwindl0** [comment]
Christopher, do you mean that from inside your eclipse, you use the File->Open menu to look for a tdml file on an arbitrary location outside of your workspace? I.o. copying the file in a project and working from there (as you describe on the wiki page)?

Hadn't tried that before myself, File->Open..., but tried it now and it works for me, for one of the 2 Opens I find in my menu :

![file_openmenu](https://cloud.githubusercontent.com/assets/6461921/13548966/a5a1e0fc-e2fc-11e5-9ba5-47986827fb8f.JPG)

The bottom one works, but looks for a *.triq extension by default i.o. *.tdml.
The top one fails with the error you mention.

I'll need to  find out where those two Open... variations are coming from.

**Comment by cxbrooks** [comment]
Yes, I have the same behavior where the upper Open does not work, the lower one does work.  I'm trying to open an arbitrary file located outside the workspace.

**Comment by erwindl0** [comment]
Christopher, fix done on master to allow opening files outside of the workspace (via File>Open).

Can you try it out as well?

**Comment by cxbrooks** [comment]
Thanks. This works for me.

I created a simple model, then copied it to ~/tmp/myModel.tdml.

I then did File->Open and was able to open the file.

Note that we still have two Open choices in the File Menu, but they both work.

We can either leave this issue open pending fixing it so that there is only one File menu or open a new issue.  Feel free to do either.

**Comment by erwindl0** [comment]
I removed the default generated EMF editor bundle from the packaged product.
That's the one resulting in the duplicate menu entries.

Can you check with the updated master contents?

**Comment by cxbrooks** [comment]
The duplicate Open menu choice is gone, so I'm closing this.
