### ISSUE TITLE
Mac OS X: updates to parameter values not preserved

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#7]
When I change the parameter value of a Const actor, the new value is not preserved.

See https://github.com/eclipse/triquetrum/wiki/Getting-Started

This seems to be a Mac-specific issue, see https://www.eclipse.org/forums/index.php/t/1073404/

**Comment by erwindl0** [comment]
Davy De Durpel tried a fix in NamedObjDialog and gave me a huge "yihaaa" yell/email, so that seems to be the right thing to get this fixed ;-)
I will commit it for him.

**Comment by cxbrooks** [comment]
Fixed!
