### ISSUE TITLE
Open Ipzilla issues for Triquetrum third party code

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#70]
Here are the Triquetrum Ipzilla issues:

https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10439 - diva
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10440 - ptolemy.actor.gui
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10441 - ptolemy.actor.lib
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10442 - ptolemy.core
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10443 - ptolemy.sdf
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10444 - ptolemy.gui
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10445 - ptolemy.moml
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10446 - org.ptolemy.commons
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10856 - ptolemy.domains.process

To close this issue, the above need to be closed.

Ideally, this would happen by the ScienceAutumn2016Release.

**Comment by cxbrooks** [comment]
Below is the list of Triquetrum CQs in order of priority.

Stable CQs that are unlikely to change
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10439 - diva
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10446 - org.ptolemy.commons
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10443 - ptolemy.sdf
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10856 - ptolemy.domains.process

More stable
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10445 - ptolemy.moml
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10442 - ptolemy.core

Could see changes
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10441 - ptolemy.actor.lib
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10444 - ptolemy.gui

The most unstable:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10440 - ptolemy.actor.gui

**Comment by jayjaybillings** [comment]
Just reviewed this with Andrea Ross. I suggested that this prioritized list be communicated to the IP team for Triquetrum.

**Comment by erwindl0** [comment]
I have uploaded the current versions of the above ptolemy sources in the CQs

**Comment by cxbrooks** [comment]
Below is the list of Triquetrum CQs in order of priority.

Stable CQs that are unlikely to change:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10439 - diva - returned to devel on 8/16, returned to IP on 8/16
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10446 - org.ptolemy.commons
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10443 - ptolemy.sdf
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10856 - ptolemy.domains.process

More stable:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10445 - ptolemy.moml
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10442 - ptolemy.core

Could see changes:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10441 - ptolemy.actor.lib - returned to devel on 8/16, returned to IP on 8/16
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10444 - ptolemy.gui - returned to devel on 8/16, returned to IP on 8/17

The most unstable:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10440 - ptolemy.actor.gui

Recently added:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11837 - Apache HttpClient 3.1 (PB1765) (PB CQ1857)

**Comment by cxbrooks** [comment]
Below is the list of Triquetrum CQs in order of priority.

Stable CQs that are unlikely to change:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10439 - diva - 652K Jar - returned to devel on 8/16, returned to IP on 8/16
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10446 - org.ptolemy.commons - 8K Jar
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10443 - ptolemy.sdf - 142K Jar
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10856 - ptolemy.domains.process - 70K Jar

More stable:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10445 - ptolemy.moml - 260K Jar
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10442 - ptolemy.core - 1500K Jar

Could see changes:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10441 - ptolemy.actor.lib - 320K Jar - returned to devel on 8/16, returned to IP on 8/16
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10444 - ptolemy.gui - 457K Jar - returned to devel on 8/16, returned to IP on 8/17

The most unstable:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10440 - ptolemy.actor.gui - 15K Jar

Recently added:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11837 - Apache HttpClient 3.1 (PB1765) (PB CQ1857) - awaiting pmc

3424K Jar files total
1459K returned to devel and then returned to IP

**Comment by cxbrooks** [comment]
Good news!  Most of the CQs have been approved, we have one remaining Ptolemy IP CQ and one Apache IP CQ.

Below is the list of Triquetrum CQs in order of priority.

Stable CQs that are unlikely to change:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10439 - diva - 652K Jar - Approved!
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10446 - org.ptolemy.commons - 8K Jar - Approved!
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10443 - ptolemy.sdf - 142K Jar - Approved!
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10856 - ptolemy.domains.process - 70K Jar - Approved!

More stable:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10445 - ptolemy.moml - 260K Jar - Approved!
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10442 - ptolemy.core - 1500K Jar - Approved!

Could see changes:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10441 - ptolemy.actor.lib - 320K Jar - Approved!
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10444 - ptolemy.gui - 457K Jar - returned to devel on 8/16, returned to IP on 8/17, returned to devel on 8/23.

The most unstable:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10440 - ptolemy.actor.gui - 15K Jar - Approved!

Recently added:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11837 - Apache HttpClient 3.1 (PB1765) (PB CQ1857) - awaiting pmc

**Comment by erwindl0** [comment]
Great news!

The Apache one should pass without issues as it's a simple piggyback CQ.
It's a last piece for the CQs related to the XML-RPC Python integration 
(that were approved already).

regards
erwin

Op 8/23/2016 om 6:53 PM schreef Christopher Brooks:

**Comment by cxbrooks** [comment]
The Ptolemy source CQs have been approved!

https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11837 "Apache HttpClient 3.1 (PB1765) (PB CQ1857)" is the remaining IP issue.

**Comment by cxbrooks** [comment]
This is complete, all the Ptolemy source CQs and others that are part of the initial checkin have been approved.
