### ISSUE TITLE
Triquetrum First Release: 21st October 2016

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#71]
Our goal is to have a first release of Triquetrum on 21st October 2016 as part of a combined [Eclipse Science Workgroup](21st October 2016) release.

In the perfect world, we would have Bug #18: Create a CapeCode Triquetrum product fixed.

Also, it would be helpful, if the Bug #70: Open Ipzilla issues for Triquetrum third party code was closed.

**Comment by cxbrooks** [comment]
We submitted the release materials and the IP Log.  

[Bug 501944 - [release] technology.triquetrum 0.1.0 ](https://bugs.eclipse.org/bugs/show_bug.cgi?id=501944) has been created.

**Comment by cxbrooks** [comment]
The IPLog is at https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12005

**Comment by erwindl0** [comment]
IPLog was approved today!

**Comment by cxbrooks** [comment]
At this point, we have one other remaining bug for the Science2016Release Milestone: Bug #113 Need a way for OSGi Bundles to add MoML filters.

Erwin and I discussed Bug #113 and he will update it.

At this point, we have a M1 release available on the [Eclipse download site](https://projects.eclipse.org/projects/technology.triquetrum/downloads)

After we get feedback about the release documents, we can create a RC1 build.

Probably the way to do this is to create a branch on this bug, update the version numbers, commit, push, pull the changes and then run the [Triquetrum Hudson Build](https://hudson.eclipse.org/triquetrum/job/triquetrum/).  Then, once we get things working and have a final production release, we need to update the Hudson Build so that we don't overwrite our 0.1.0 release and then create a new branch that has the new version numbers and commit, push and pull request that new version.  The devil is in the details of the versioning.  

See the [Tycho Versioning Plugin](https://eclipse.org/tycho/sitedocs/tycho-release/tycho-versions-plugin/plugin-info.html) for one way to do this.

To close this bug, we need to have the Triquetrum 0.1.0 downloads available and the nightly build building nightly installers.

**Comment by erwindl0** [comment]
The release was done!
