### ISSUE TITLE
Workflow editor leaks SWT resources

### ISSUE THREAD

**Issue by ChrisOnJava** [eclipse/triquetrum#73]
PtolemyModelElementShape's DrawingStrategy-is never dispose the allocated Fonts and Colors (tested with Sleak SWT tool). After a while eclipse become totally unusable. (org.eclipse.swt.SWTError: No more handles)
I'm working on a fix.

**Comment by erwindl0** [comment]
Great, thanks! 

I didn't get around yet to build/use font/color registries.

**Comment by ChrisOnJava** [comment]
The question is the scope of the registry: editor-wide, or 'local'. I suggest a local solution. Only hold the resources until they are needed.

**Comment by erwindl0** [comment]
As I have the impression that Graphiti re-renders diagram components very often, maybe a "diagram"-scope would be best?
E.g. linked to the org.eclipse.triquetrum.workflow.editor.TriqDiagramTypeProvider instance for each active/open diagram?

**Comment by erwindl0** [comment]
Hi Krisztian,

Any luck/time to continue on this and/or on the graphiti custom rendering stuff?
Just let me know if you won't have the time in the coming days/weeks, then I can adapt my work plan if needed.

cheers
erwin

**Comment by ChrisOnJava** [comment]
Erwin, sorry for being late. We have a deadline at my company in the middle of this week. I try to finish this in this week (include the weekend).

**Comment by erwindl0** [comment]
no worries, no need to work on this in the weekend! (unless you enjoy it of course ;-) )

**Comment by erwindl0** [comment]
Krisztian, do you think this is still feasible for you? 
If not, just let me know.
It might also be good to have a direct email contact i.o. mailing-via-issues ;-)
you can reach me with my useriD on gmail

**Comment by erwindl0** [comment]
I have introduced a JFace ResourceManager in the TriqDiagramBehavior. It is disposed when closing the diagram & makes sure that redrawing identical fonts/colors reuses the previously created instances. So two improvements in one shot.

The resource manage is used in the drawing strategies.

I've done some manual testing with sleak and it seems to behave correctly now.

Krisztian, if you still feel like it, you're welcome to do e.g. a code review for that part?

**Comment by erwindl0** [comment]
My changes should have fixed this issue (was tested as far as I can). No feedback since > 1 month. closing the issue.
