### ISSUE TITLE
Support for Actor Oriented Classes

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#78]
Triquetrum needs to be able to support Actor-Oriented Classes, which is where a chunk of functionality is defined as a set of actors and that chunk can be extended.

Details to follow.

**Comment by cxbrooks** [comment]
[From discussion with Erwin]

In Ptolemy, the Sinewave composite is an actor-oriented class, so supporting this is fairly important.  However, we could also substitute in a non-actor-oriented class.

One possibility would be to initially only support setting parameters of actor-oriented classes, which is how Passerelle works.

Another issue is where do we store classes.  In Ptolemy, the AOC files are stored on the classpath, which is tricky in a OSGi environment.  This ties in to how do we store files in Triquetrum?  One file or two files?

**Comment by cxbrooks** [comment]
It could be that Xtext and multi page editors could help here. 

Multipage editors are used for the xml plugin editor.

Multipage editors were used for the Passerelle editor and to drill down.

Graphiti can be embedded anywhere.

Perhaps we should look at what ELK is doing?

**Comment by erwindl0** [comment]
I'll try to start using the WorkflowRepositoryService API to store/retrieve AOCs. It will imply providing at least a simple Preferences page (cfr #183) to be able to configure the physical location of the repository.

For the moment the repo API is still defined on Ptolemy II CompositeActor etc, which is handy for a first phase : just try to support using AOCs that have been prepared with Ptolemy/Vergil, and being able to configure AOC parameters.

In a second phase , we must be able to create/edit AOCs in Triquetrum and then the repo API must be able to handle Triquetrum models besides or i.o. Ptolemy ones.

**Comment by erwindl0** [comment]
Current ideas and status has been described on the wiki : https://wiki.eclipse.org/Triquetrum/Actor_Oriented_Classes

**Comment by erwindl0** [comment]
I’ll add something to create the (empty at first) file when it’s missing + some preferences entries to change its location & to refresh the LibraryManager.

(a bit similar to handling a Maven settings file in the prefs)

**Comment by erwindl0** [comment]
first level of AOC support done, for reusing existing AOCs via the User Library.

Next phases will be handled in separate issues.
