### ISSUE TITLE
Copy and paste of actors does not work

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#87]
Under Mac OS X, using the devel head, I can highlight the actors in a graph, but copy and paste do no work.

**Comment by erwindl0** [comment]
copy/paste related code was not yet migrated from Passerelle's graphiti trials

**Comment by cxbrooks** [comment]
It turns out that there is quite a bit to copy and paste in Ptolemy II.

See ptolemy/vergil/basic/BasicGraphFrame.java for the CopyAction() and PasteAction()

* When we copy an actor that refers to a variable into a container that does not define that variable, then the variable should be created in the container.  See ptolemy/moml/MoMLVariableChecker.java and ptolemy/data/expr/UndefinedConstantOrIdentifierException.java

* Typically, changes are queued up as MoMLChangeRequests.  See ptolemy.kernel.undo for how to undo those changes.

* See ptolemy/vergil/OffsetMoMLChangeRequest.java for how to offset objects that are created in the toplevel.

**Comment by erwindl0** [comment]
basic copy/paste of actors, parameters, connections works within and across diagrams.

more advanced things like mentioned by Christopher not yet done.

**Comment by cxbrooks** [comment]
Basic copy and paste works (need to verify).

However, if an actor refers to a parameter in the container, then the parameter is not copied and pasted along with the actor.

**Comment by erwindl0** [comment]
I would propose that, if basic copy/paste functionality has been verified to our satisfaction, this is sufficient for the release.

We could then close this and create new issue for "advanced copy/paste behavior"?

**Comment by cxbrooks** [comment]
Rather than closing this bug about copy and paste, let's move the milestone to the Spring 2017 release.  It is fairly important that when copying an actor, we copy the parameters as well.

**Comment by erwindl0** [comment]
I would try to use a slightly adapted ptolemy.moml.MoMLVariableChecker to figure out variables that are referred to. 

I.o. letting it create a moml with all of them, it will also collect lists of the elements that must be copied along, so these can then be used in Triquetrum's copy code.

I'm not sure about what to do with the handling of missing classes which also seems to be part of the generated moml. But for Triquetrum that would need to wait until the implementation of actor-oriented classes is done (#78).

**Comment by erwindl0** [comment]
MoMLVariableChecker served as inspiration, but was too closely linked to using MoML fragments and change requests to be able to use it in Triquetrum.

The logic has been rebuilt in ModelElementPasteFeature.

**Comment by cxbrooks** [comment]
I'll test this and report back.

**Comment by erwindl0** [comment]
I'll close this, as in my testing it seems to behave as expected.
If any related issue is found, we can open a new specific issue for that.
