### ISSUE TITLE
Mac OS X: actor parameter values are not visible in the icons

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#89]
Under Mac OS X: actor parameter values are not visible in the icons.
Compare [https://wiki.eclipse.org/File:TriquetrumScreenShot.png](https://wiki.eclipse.org/File:TriquetrumScreenShot.png) with [https://wiki.eclipse.org/File:TriquetrumScreenShotSinePlot.png](https://wiki.eclipse.org/File:TriquetrumScreenShotSinePlot.png)

**Comment by erwindl0** [comment]
Op 04/06/2016 om 03:57 schreef Christopher Brooks:
>
> Under Mac OS X: actor parameter values are not visible in the icons.
> Compare https://wiki.eclipse.org/File:TriquetrumScreenShot.png with 
> https://wiki.eclipse.org/File:TriquetrumScreenShotSinePlot.png
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/eclipse/triquetrum/issues/89>, or mute the thread 
> <https://github.com/notifications/unsubscribe/AGKZ4Yp_xq3bKK7hVl6q81otAzMmihu8ks5qINt8gaJpZM4IuBov>.
>
I removed the parameters from the actor icons a while ago ;-)

So it's not an issue, not specific to your MacOSX, it's deliberate.

Reasons :

- the name & value doesn't fit anyway

- custom icons don't show them neither

- they were the reason that double-click didn't always work well to open 
the config panel


If you would like to get them back, then I can add them.

But you're correct, the wiki screenshots need some updates

cheers
erwin

**Comment by cxbrooks** [comment]
To close this, the wiki needs to be updated with screenshots that don't show actor parameter values.

**Comment by cxbrooks** [comment]
Below are the pages that need updates
- [ ] http://wiki.eclipse.org/Triquetrum/Opening_A_Model - Depends on Bug #220
- [ ] http://wiki.eclipse.org/Triquetrum/CapeCode
- [ ] http://wiki.eclipse.org/Triquetrum/Extending_Triquetrum 
- [ ] http://wiki.eclipse.org/File:TriquetrumScreenShot2Feb2016.jpg
- [ ] http://wiki.eclipse.org/File:TriquetrumScreenShotSinePlot.png

**Comment by cxbrooks** [comment]
We have updated all the images.  Closing.
