### ISSUE TITLE
Use Target Platform Definition DSL and Generator to define target platform 

### ISSUE THREAD

**Issue by jonahkichwacoders** [eclipse/triquetrum#92]
_Originally created at bugzilla before I remembered that Triq has its own tracker: https://bugs.eclipse.org/bugs/show_bug.cgi?id=496322_

Instead of using .target files directly, instead use tpd files (Target Platform Definition DSL and Generator files, from https://github.com/mbarbero/fr.obeo.releng.targetplatform). This allows a textual representation of the target platform that is easier to read, edit and merge than the xml one.

Pull request on the way for this, along with the Python AnalysisRPC work.

**Comment by erwindl0** [comment]
Great idea!
I had read about this, but didn't get around to try it out yet.

**Comment by jonahkichwacoders** [comment]
I added (commented out) the new instructions to https://wiki.eclipse.org/Triquetrum/Building_From_Sources#Building . It should be un-commented once this bug is resolved.
