### ISSUE TITLE
Can't change a port from a non-multiport to a multiport

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#95]
1. Start up Triquetrum
2. Search for a RecordDisassembler and drag it in to the canvas
3. Double click on the RecordDisassembler and click on Output ports
4. Click on the + button, add an output port named "output".  Do not click on multiport.
5. Click OK. The port appears as a filled in triangle
6. Double click on the RecordDisassembler and click on Output ports
7. In the "output" port line, click on Multiport
8. Click OK.  The port should appear as a hollow triangle, but it does not.

**Comment by erwindl0** [comment]
Internally the port "mode" change is picked up, but : 
- port icon is not updated indeed
- editor is not marked as dirty (this seems to be a general issue now for changes done via EMF forms that don't cause graphical updates)

I've found a way to intercept such changes with graphiti features and will investigate more.

**Comment by cxbrooks** [comment]
I checked and I can now change a port to a multiport.

I created Bug #158.
